// ============================================================
// generator.js — 統合版 (Architecture A + B merged)
// ============================================================

const EAGenerator = {

  // ==================== Main Dispatcher ====================
  generate: function(state) {
    const p = state.platform || 'mt4';
    if (p === 'mt5') {
      return this.generateMT5(state);
    } else {
      return this.generateMT4(state);
    }
  },

  generateMT4: function(state) {
    let code = '';
    code += this.generateHeaderMT4(state);
    code += this.generateInputParametersMT4(state);
    code += this.generateOnInitMT4(state);
    code += this.generateOnTickMT4(state);
    code += this.generateHelperFunctionsMT4(state);
    return code;
  },

  generateMT5: function(state) {
    let code = '';
    code += this.generateHeaderMT5(state);
    code += this.generateInputParametersMT5(state);
    code += this.generateIndicatorHandlesMT5(state);
    code += this.generateOnInitMT5(state);
    code += this.generateOnTickMT5(state);
    code += this.generateIndicatorFunctionsMT5(state);
    code += this.generateHelperFunctionsMT5(state);
    return code;
  },

  // ==================== Price Helpers ====================
  _close(shift) { return `iClose(Symbol(),Period(),${shift})`; },
  _open(shift)  { return `iOpen(Symbol(),Period(),${shift})`; },
  _high(shift)  { return `iHigh(Symbol(),Period(),${shift})`; },
  _low(shift)   { return `iLow(Symbol(),Period(),${shift})`; },

  _closeMT5(arrName, count) {
    return `double ${arrName}[]; ArraySetAsSeries(${arrName},true); CopyClose(Symbol(),Period(),0,${count},${arrName});`;
  },
  _openMT5(arrName, count) {
    return `double ${arrName}[]; ArraySetAsSeries(${arrName},true); CopyOpen(Symbol(),Period(),0,${count},${arrName});`;
  },
  _highMT5(arrName, count) {
    return `double ${arrName}[]; ArraySetAsSeries(${arrName},true); CopyHigh(Symbol(),Period(),0,${count},${arrName});`;
  },
  _lowMT5(arrName, count) {
    return `double ${arrName}[]; ArraySetAsSeries(${arrName},true); CopyLow(Symbol(),Period(),0,${count},${arrName});`;
  },

  // ==================== [G-010] Header MT4 ====================
  generateHeaderMT4: function(state) {
    const name = state.eaName || 'MyEA';
    return `//+------------------------------------------------------------------+
//| ${name}.mq4
//| Generated by EA Labo
//+------------------------------------------------------------------+
#property copyright "EA Labo"
#property link      ""
#property version   "1.00"
#property strict

`;
  },

  // ==================== [G-011] Header MT5 ====================
  generateHeaderMT5: function(state) {
    const name = state.eaName || 'MyEA';
    return `//+------------------------------------------------------------------+
//| ${name}.mq5
//| Generated by EA Labo
//+------------------------------------------------------------------+
#property copyright "EA Labo"
#property link      ""
#property version   "1.00"

#include <Trade\\Trade.mqh>
CTrade trade;

`;
  },

  // ==================== [G-020] Input Parameters MT4 ====================
  generateInputParametersMT4: function(state) {
    let code = '//--- 入力パラメータ（ユーザー設定値） ---\n';
    code += `extern int    MagicNumber    = ${state.magicNumber || 12345};\n`;
    code += `extern double LotSize        = ${state.lotSize || 0.01};\n`;
    code += `extern int    TakeProfit     = ${state.takeProfit || 0};\n`;
    code += `extern int    StopLoss       = ${state.stopLoss || 0};\n`;
    code += `extern int    Slippage       = ${state.slippage || 3};\n`;

        if (state.useTrailing) {
      code += `extern int    TrailingStart  = ${state.trailingStart || 20};\n`;
      code += `extern int    TrailingWidth  = ${state.trailingWidth || 15};\n`;
      code += `extern int    TrailingStep   = ${state.trailingStep || 10};\n`;
    }
    if (state.useSpreadFilter) {
      code += `extern int    MaxSpread      = ${state.maxSpread || 20};\n`;
    }
    if (state.entryCooldown > 0) {
      code += `extern int    EntryCooldown  = ${state.entryCooldown || 0};\n`;
    }
    if (state.useMagicStopOrder) {
      code += `extern double MagicStopAmount = ${state.magicStopAmount || 10000};\n`;
      code += `extern int    MagicStopType   = ${state.magicStopType === 'buy' ? 1 : (state.magicStopType === 'sell' ? 2 : 0)}; // 0:Both, 1:Buy, 2:Sell\n`;
    }

    // Strategy parameters
    if (state.strategies && state.strategies.includes('nanpin')) {
      const p = state.positionParams || {};
      code += `extern int    NanpinInterval = ${p.nanpinInterval || 20};\n`;
      code += `extern int    NanpinMax      = ${p.nanpinMax || 5};\n`;
      code += `extern double NanpinTargetProfit = ${state.nanpinTargetProfit || 0};\n`;
    }
    if (state.useMonthFilter) {
      code += `extern bool   UseMonthFilter = true;\n`;
      code += `extern int    MonthStartDays = ${state.monthStartDays || 0};\n`;
      code += `extern int    MonthEndDays   = ${state.monthEndDays || 0};\n`;
    }
    if (state.strategies && state.strategies.includes('martingale')) {
      const p = state.positionParams || {};
      code += `extern double MartingaleMultiplier = ${p.martingaleMultiplier || 2.0};\n`;
      code += `extern int    MartingaleMax  = ${p.martingaleMax || 5};\n`;
    }

    if (state.riskPercent > 0) {
      code += `extern double RiskPercent    = ${state.riskPercent || 1.0};\n`;
    }

    if (state.useNewsFilter) {
      code += `extern int    NewsStopBefore = ${state.newsStopMinutesBefore || 60};\n`;
      code += `extern int    NewsStopAfter  = ${state.newsStopMinutesAfter || 60};\n`;
      code += `extern string NewsSeverity   = "${state.newsSeverity || 'low'}"; // high, medium, low\n`;
    }

    code += '\n';
    code += '//--- グローバル変数 ---\n';
    code += 'datetime lastBarTime = 0;\n';
    code += 'int      barCount    = 0;\n';
    if (state.strategies && state.strategies.includes('martingale')) {
      code += 'int      martingaleCount = 0;\n';
      code += 'double   martingaleLot   = 0;\n';
    }
    code += '\n';
    return code;
  },

  // ==================== [G-021] Input Parameters MT5 ====================
  generateInputParametersMT5: function(state) {
    let code = '//--- 入力パラメータ（ユーザー設定値） ---\n';
    code += `input int    MagicNumber    = ${state.magicNumber || 12345};\n`;
    code += `input double LotSize        = ${state.lotSize || 0.01};\n`;
    code += `input int    TakeProfit     = ${state.takeProfit || 0};\n`;
    code += `input int    StopLoss       = ${state.stopLoss || 0};\n`;
    code += `input int    Slippage       = ${state.slippage || 3};\n`;

        if (state.useTrailing) {
      code += `input int    TrailingStart  = ${state.trailingStart || 20};\n`;
      code += `input int    TrailingWidth  = ${state.trailingWidth || 15};\n`;
      code += `input int    TrailingStep   = ${state.trailingStep || 10};\n`;
    }
    if (state.useSpreadFilter) {
      code += `input int    MaxSpread      = ${state.maxSpread || 20};\n`;
    }
    if (state.entryCooldown > 0) {
      code += `input int    EntryCooldown  = ${state.entryCooldown || 0};\n`;
    }
    if (state.useMagicStopOrder) {
      code += `input double MagicStopAmount = ${state.magicStopAmount || 10000};\n`;
      code += `input int    MagicStopType   = ${state.magicStopType === 'buy' ? 1 : (state.magicStopType === 'sell' ? 2 : 0)}; // 0:Both, 1:Buy, 2:Sell\n`;
    }

    if (state.strategies && state.strategies.includes('nanpin')) {
      const p = state.positionParams || {};
      code += `input int    NanpinInterval = ${p.nanpinInterval || 20};\n`;
      code += `input int    NanpinMax      = ${p.nanpinMax || 5};\n`;
      code += `input double NanpinTargetProfit = ${state.nanpinTargetProfit || 0};\n`;
    }
    if (state.useMonthFilter) {
      code += `input bool   UseMonthFilter = true;\n`;
      code += `input int    MonthStartDays = ${state.monthStartDays || 0};\n`;
      code += `input int    MonthEndDays   = ${state.monthEndDays || 0};\n`;
    }
    if (state.strategies && state.strategies.includes('martingale')) {
      const p = state.positionParams || {};
      code += `input double MartingaleMultiplier = ${p.martingaleMultiplier || 2.0};\n`;
      code += `input int    MartingaleMax  = ${p.martingaleMax || 5};\n`;
    }

    if (state.riskPercent > 0) {
      code += `input double RiskPercent    = ${state.riskPercent || 1.0};\n`;
    }

    code += '\n';
    code += '//--- グローバル変数 ---\n';
    code += 'datetime lastBarTime = 0;\n';
    code += 'int      barCount    = 0;\n';
    if (state.strategies && state.strategies.includes('martingale')) {
      code += 'int      martingaleCount = 0;\n';
      code += 'double   martingaleLot   = 0;\n';
    }
    code += '\n';
    return code;
  },

  // ==================== [G-030] OnInit MT4 ====================
  generateOnInitMT4: function(state) {
    let code = '//+------------------------------------------------------------------+\n';
    code += '//| 初期化処理 (EA起動時に1回だけ実行)                                |\n';
    code += '//+------------------------------------------------------------------+\n';
    code += 'int OnInit()\n{\n';
    
    // Account Lock
    if (state.useAccountLock && state.lockAccountId) {
      code += '   if(AccountNumber() != ' + state.lockAccountId + ') {\n';
      code += '      Alert("Invalid Account Number! This EA is locked to account: ' + state.lockAccountId + '");\n';
      code += '      return(INIT_FAILED);\n';
      code += '   }\n';
    }

    // Expiry Lock
    if (state.useExpiryLock && state.lockExpiryDate) {
      const mqlDate = state.lockExpiryDate.replace(/-/g, '.');
      code += '   if(TimeCurrent() >= D\'' + mqlDate + '\') {\n';
      code += '      Alert("EA Expired! Please contact the developer for renewal.");\n';
      code += '      return(INIT_FAILED);\n';
      code += '   }\n';
    }

    code += '   Print("EA initialized: ' + (state.eaName || 'MyEA') + '");\n';
    code += '   return(INIT_SUCCEEDED);\n';
    code += '}\n\n';

    code += 'void OnDeinit(const int reason)\n{\n';
    code += '   Print("EA removed: ' + (state.eaName || 'MyEA') + '");\n';
    code += '}\n\n';
    return code;
  },

  // ==================== [G-031] OnInit MT5 ====================
  generateOnInitMT5: function(state) {
    let code = '//+------------------------------------------------------------------+\n';
    code += '//| 初期化処理 (EA起動時に1回だけ実行)                                |\n';
    code += '//+------------------------------------------------------------------+\n';
    code += 'int OnInit()\n{\n';

    // Account Lock
    if (state.useAccountLock && state.lockAccountId) {
      code += '   if(AccountInfoInteger(ACCOUNT_LOGIN) != ' + state.lockAccountId + ') {\n';
      code += '      Alert("Invalid Account Number! This EA is locked to account: ' + state.lockAccountId + '");\n';
      code += '      return(INIT_FAILED);\n';
      code += '   }\n';
    }

    // Expiry Lock
    if (state.useExpiryLock && state.lockExpiryDate) {
      const mqlDate = state.lockExpiryDate.replace(/-/g, '.');
      code += '   if(TimeCurrent() >= D\'' + mqlDate + '\') {\n';
      code += '      Alert("EA Expired! Please contact the developer for renewal.");\n';
      code += '      return(INIT_FAILED);\n';
      code += '   }\n';
    }

    code += '   trade.SetExpertMagicNumber(MagicNumber);\n';
    code += '   trade.SetDeviationInPoints(Slippage);\n';
    code += '   \n';
    code += '   //--- Indicator Initializations\n';
    code += '   if(!InitializeIndicators()) return(INIT_FAILED);\n\n';
    code += '   Print("EA initialized: ' + (state.eaName || 'MyEA') + '");\n';
    code += '   return(INIT_SUCCEEDED);\n';
    code += '}\n\n';

    code += 'void OnDeinit(const int reason)\n{\n';
    code += '   Print("EA removed: \' + (state.eaName || \'MyEA\') + \'");\n';
    code += '}\n\n';
    return code;
  },

  // ==================== [G-032] Indicator Handles MT5 ====================
  generateIndicatorHandlesMT5: function(state) {
    let code = '//--- Indicator Handles\n';
    const allConditions = [
      ...(state.buyConditions || []), 
      ...(state.sellConditions || []),
      ...(state.exitConditions || [])
    ];

    let initCode = 'bool InitializeIndicators()\n{\n';

    allConditions.forEach((c, idx) => {
      if (c.category !== 'indicator') return;
      const ind = c.indicator || c.id || 'ma';
      const params = c.params || {};
      const handleName = `hInd_${idx}`;
      
      code += `int ${handleName} = INVALID_HANDLE;\n`;

      switch(ind) {
        case 'ma':
          initCode += `   ${handleName} = iMA(Symbol(), (ENUM_TIMEFRAMES)${c.condTimeframe || 0}, ${params.period || 14}, 0, (ENUM_MA_METHOD)(${params.method || 0}), PRICE_CLOSE);\n`;
          break;
        case 'rsi':
          initCode += `   ${handleName} = iRSI(Symbol(), (ENUM_TIMEFRAMES)${c.condTimeframe || 0}, ${params.period || 14}, PRICE_CLOSE);\n`;
          break;
        case 'stochastic':
          {
            const k = params.kPeriod || params.stoch_k || 5;
            const d = params.dPeriod || params.stoch_d || 3;
            const sl = params.slowing || params.stoch_slowing || 3;
            initCode += `   ${handleName} = iStochastic(Symbol(), (ENUM_TIMEFRAMES)${c.condTimeframe || 0}, ${k}, ${d}, ${sl}, MODE_SMA, STO_LOWHIGH);\n`;
          }
          break;
        case 'macd':
          initCode += `   ${handleName} = iMACD(Symbol(), (ENUM_TIMEFRAMES)${c.condTimeframe || 0}, ${params.fastPeriod || 12}, ${params.slowPeriod || 26}, ${params.signalPeriod || 9}, PRICE_CLOSE);\n`;
          break;
        case 'bollinger':
          initCode += `   ${handleName} = iBands(Symbol(), (ENUM_TIMEFRAMES)${c.condTimeframe || 0}, ${params.period || 20}, 0, ${params.deviation || 2.0}, PRICE_CLOSE);\n`;
          break;
        case 'ichimoku':
          initCode += `   ${handleName} = iIchimoku(Symbol(), (ENUM_TIMEFRAMES)${c.condTimeframe || 0}, ${params.tenkan || 9}, ${params.kijun || 26}, ${params.senkou || 52});\n`;
          break;
        case 'cci':
          initCode += `   ${handleName} = iCCI(Symbol(), (ENUM_TIMEFRAMES)${c.condTimeframe || 0}, ${params.period || 14}, PRICE_TYPICAL);\n`;
          break;
      }
      initCode += `   if(${handleName} == INVALID_HANDLE) { Print("Failed to create handle for condition ${idx}"); return false; }\n`;
    });

    initCode += '   return true;\n}\n\n';
    return code + '\n' + initCode;
  },

  // ==================== [G-033] Indicator Check Functions MT5 ====================
  generateIndicatorFunctionsMT5: function(state) {
    let code = '//--- Indicator Check Functions\n';
    
    const generateCheck = (conditions, direction) => {
      conditions.forEach((c, idx) => {
        if (c.category !== 'indicator') return;
        const ind = c.indicator || c.id || 'ma';
        const indAlias = (ind === 'stochastic' ? 'Stoch' : this._capitalize(ind));
        const params = c.params || (c.detail && typeof c.detail === 'object' ? c.detail : {});
        const type = c.conditionType || c.type || '';
        const shift = parseInt(c.shift) || 1;
        const isBuy = (direction === 'buy');
        const funcName = isBuy ? `Check${indAlias}_Buy_${idx}` : `Check${indAlias}_Sell_${idx}`;
        const handleName = `hInd_${idx}`;

        code += `bool ${funcName}()\n{\n`;
        code += `   double buffer0[], buffer1[];\n`;
        
        switch(ind) {
          case 'ma':
            code += `   if(CopyBuffer(${handleName}, 0, ${shift}, 2, buffer0) < 2) return false;\n`;
            if (type === 'cross_up') code += `   return (buffer0[0] > iClose(Symbol(), (ENUM_TIMEFRAMES)${c.condTimeframe || 0}, ${shift}) && buffer0[1] <= iClose(Symbol(), (ENUM_TIMEFRAMES)${c.condTimeframe || 0}, ${shift+1}));\n`;
            else if (isBuy)          code += `   return (iClose(Symbol(), (ENUM_TIMEFRAMES)${c.condTimeframe || 0}, ${shift}) > buffer0[0]);\n`;
            else                     code += `   return (iClose(Symbol(), (ENUM_TIMEFRAMES)${c.condTimeframe || 0}, ${shift}) < buffer0[0]);\n`;
            break;
          case 'rsi':
            code += `   if(CopyBuffer(${handleName}, 0, ${shift}, 1, buffer0) < 1) return false;\n`;
            if (isBuy) code += `   return (buffer0[0] < ${params.oversold || 30});\n`;
            else       code += `   return (buffer0[0] > ${params.overbought || 70});\n`;
            break;
          case 'stochastic':
            {
              const lv = params.level || params.stoch_level || params.overbought || params.oversold || 20;
              code += `   if(CopyBuffer(${handleName}, 0, ${shift}, 2, buffer0) < 2) return false;\n`;
              code += `   if(CopyBuffer(${handleName}, 1, ${shift}, 2, buffer1) < 2) return false;\n`;
              if (type === 'cross_up')   code += `   return (buffer0[0] > buffer1[0] && buffer0[1] <= buffer1[1]);\n`;
              else if (type === 'cross_down') code += `   return (buffer0[0] < buffer1[0] && buffer0[1] >= buffer1[1]);\n`;
              else if (type === 'above_level' || type === 'overbought') code += `   return (buffer0[0] > ${lv});\n`;
              else if (type === 'below_level' || type === 'oversold')   code += `   return (buffer0[0] < ${lv});\n`;
              else if (isBuy) code += `   return (buffer0[0] < 20);\n`;
              else            code += `   return (buffer0[0] > 80);\n`;
            }
            break;
          case 'ichimoku':
            code += `   if(CopyBuffer(${handleName}, 0, ${shift}, 1, buffer0) < 1) return false; // Tenkan\n`;
            code += `   if(CopyBuffer(${handleName}, 1, ${shift}, 1, buffer1) < 1) return false; // Kijun\n`;
            if (type === 'tenkan_kijun') {
              if (isBuy) code += `   return (buffer0[0] > buffer1[0]);\n`;
              else       code += `   return (buffer0[0] < buffer1[0]);\n`;
            } else if (type === 'below_kumo') {
              code += `   if(CopyBuffer(${handleName}, 2, ${shift}, 1, buffer0) < 1) return false; // SpanA\n`;
              code += `   if(CopyBuffer(${handleName}, 3, ${shift}, 1, buffer1) < 1) return false; // SpanB\n`;
              if (isBuy) code += `   return (iClose(Symbol(), (ENUM_TIMEFRAMES)${c.condTimeframe || 0}, ${shift}) < MathMin(buffer0[0], buffer1[0]));\n`;
              else       code += `   return (iClose(Symbol(), (ENUM_TIMEFRAMES)${c.condTimeframe || 0}, ${shift}) > MathMax(buffer0[0], buffer1[0]));\n`;
            } else if (type === 'kumo_break') {
              code += `   if(CopyBuffer(${handleName}, 2, ${shift}, 2, buffer0) < 2) return false; // SpanA(0,1)\n`;
              code += `   if(CopyBuffer(${handleName}, 3, ${shift}, 2, buffer1) < 2) return false; // SpanB(0,1)\n`;
              code += `   double close0 = iClose(Symbol(), (ENUM_TIMEFRAMES)${c.condTimeframe || 0}, ${shift});\n`;
              code += `   double close1 = iClose(Symbol(), (ENUM_TIMEFRAMES)${c.condTimeframe || 0}, ${shift+1});\n`;
              if (isBuy) code += `   return (close0 > MathMax(buffer0[0],buffer1[0]) && close1 <= MathMax(buffer0[1],buffer1[1]));\n`;
              else       code += `   return (close0 < MathMin(buffer0[0],buffer1[0]) && close1 >= MathMin(buffer0[1],buffer1[1]));\n`;
            } else if (type === 'in_kumo') {
              code += `   if(CopyBuffer(${handleName}, 2, ${shift}, 1, buffer0) < 1) return false; // SpanA\n`;
              code += `   if(CopyBuffer(${handleName}, 3, ${shift}, 1, buffer1) < 1) return false; // SpanB\n`;
              code += `   double close0 = iClose(Symbol(), (ENUM_TIMEFRAMES)${c.condTimeframe || 0}, ${shift});\n`;
              code += `   return (close0 < MathMax(buffer0[0],buffer1[0]) && close0 > MathMin(buffer0[0],buffer1[0]));\n`;
            } else {
              code += `   return true;\n`;
            }
            break;
          default:
            code += '   return true;\n';
        }
        code += `}\n\n`;
      });
    };

    generateCheck(state.buyConditions || [], 'buy');
    generateCheck(state.sellConditions || [], 'sell');
    generateCheck(state.exitConditions || [], 'buy');
    
    return code;
  },

  _capitalize: function(s) {
    if (typeof s !== 'string') return '';
    return s.charAt(0).toUpperCase() + s.slice(1);
  },

  // ==================== [G-040] OnTick MT4 ====================
  generateOnTickMT4: function(state) {
    let code = '//+------------------------------------------------------------------+\n';
    code += '//| メイン処理 (ティック受信ごとに実行)                                |\n';
    code += '//+------------------------------------------------------------------+\n';
    code += 'void OnTick()\n{\n';

    // New bar detection
    code += '   //--- 新しい足が確定したかチェック（新足でなければスキップ） ---\n';
    code += '   datetime currentBar = iTime(Symbol(), Period(), 0);\n';
    code += '   if(currentBar == lastBarTime) return;\n';
    code += '   lastBarTime = currentBar;\n';
    code += '   barCount++;\n\n';

    // News Filter
    if (state.useNewsFilter) {
      code += '   //--- ニュースフィルター（指標前後でエントリー制限） ---\n';
      code += '   if(IsNewsTime()) return;\n\n';
    }

    // Spread filter
    if (state.useSpreadFilter) {
      code += '   //--- スプレッドフィルター（広すぎる場合はスキップ） ---\n';
      code += '   double spread = MarketInfo(Symbol(), MODE_SPREAD);\n';
      code += '   if(spread > MaxSpread) return;\n\n';
    }

    // Entry cooldown
    if (state.entryCooldown > 0) {
      code += '   //--- エントリークールダウン（指定本数まで取引しない） ---\n';
      code += '   if(barCount < EntryCooldown) return;\n\n';
    }

    // Trailing stop
    if (state.useTrailing) {
      code += '   //--- トレーリングストップ処理（利益方向にSLを自動追従） ---\n';
      code += '   TrailingStopFunc();\n\n';
    }

    // Auto Close by pips
    if (state.useAutoClose && (state.autoCloseProfitPips > 0 || state.autoCloseLossPips > 0)) {
      code += '   //--- pips単位の自動決済 ---\n';
      code += '   for(int ac = OrdersTotal() - 1; ac >= 0; ac--) {\n';
      code += '      if(OrderSelect(ac, SELECT_BY_POS, MODE_TRADES)) {\n';
      code += '         if(OrderSymbol() == Symbol() && OrderMagicNumber() == MagicNumber) {\n';
      code += '            double profitPips = 0;\n';
      code += '            if(OrderType() == OP_BUY)  profitPips = (Bid - OrderOpenPrice()) / Point;\n';
      code += '            if(OrderType() == OP_SELL) profitPips = (OrderOpenPrice() - Ask) / Point;\n';
      if (state.autoCloseProfitPips > 0) {
        code += '            if(profitPips >= ' + state.autoCloseProfitPips + ') {\n';
        code += '               if(OrderType() == OP_BUY)  OrderClose(OrderTicket(), OrderLots(), Bid, Slippage, clrBlue);\n';
        code += '               if(OrderType() == OP_SELL) OrderClose(OrderTicket(), OrderLots(), Ask, Slippage, clrRed);\n';
        code += '            }\n';
      }
      if (state.autoCloseLossPips > 0) {
        code += '            if(profitPips <= -' + state.autoCloseLossPips + ') {\n';
        code += '               if(OrderType() == OP_BUY)  OrderClose(OrderTicket(), OrderLots(), Bid, Slippage, clrBlue);\n';
        code += '               if(OrderType() == OP_SELL) OrderClose(OrderTicket(), OrderLots(), Ask, Slippage, clrRed);\n';
        code += '            }\n';
      }
      code += '         }\n';
      code += '      }\n';
      code += '   }\n\n';
    }

    // Auto Close by Yen (account currency)
    if (state.useAutoClose && (state.autoCloseProfitYen > 0 || state.autoCloseLossYen > 0)) {
      code += '   //--- 金額ベースの自動決済 ---\n';
      code += '   double totalPL = TotalProfit();\n';
      if (state.autoCloseProfitYen > 0) {
        code += '   if(totalPL >= ' + state.autoCloseProfitYen + ') {\n';
        code += '      CloseAllOrders();\n';
        code += '      Print("Auto close: profit target ' + state.autoCloseProfitYen + ' reached");\n';
        code += '   }\n';
      }
      if (state.autoCloseLossYen > 0) {
        code += '   if(totalPL <= -' + state.autoCloseLossYen + ') {\n';
        code += '      CloseAllOrders();\n';
        code += '      Print("Auto close: loss limit ' + state.autoCloseLossYen + ' reached");\n';
        code += '   }\n';
      }
      code += '\n';
    }

    // Indicator-based exit
    if (state.exitConditions && state.exitConditions.length > 0) {
      code += '   //--- インジケーターによる決済条件チェック ---\n';
      code += '   bool exitSignal = ' + this.generateConditionBlock(state.exitConditions, state.exitCombine, 'buy', 'mt4') + ';\n';
      code += '   if(exitSignal) {\n';
      code += '      CloseAllOrders();\n';
      code += '      Print("Indicator exit triggered");\n';
      code += '   }\n\n';
    }

    // Count positions

    // Count positions
    code += '   //--- 現在のポジション数を集計 ---\n';
    code += '   int buyCount = 0, sellCount = 0;\n';
    code += '   for(int i = OrdersTotal() - 1; i >= 0; i--) {\n';
    code += '      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {\n';
    code += '         if(OrderSymbol() == Symbol() && OrderMagicNumber() == MagicNumber) {\n';
    code += '            if(OrderType() == OP_BUY)  buyCount++;\n';
    code += '            if(OrderType() == OP_SELL) sellCount++;\n';
    code += '         }\n';
    code += '      }\n';
    code += '   }\n\n';

    // Entry conditions
    code += '   //--- エントリー条件の判定 ---\n';
    code += '   bool buySignal  = ' + this.generateConditionBlock(state.buyConditions, state.buyCombine, 'buy', 'mt4') + (state.useMonthFilter ? ' && !IsMonthFilterActive()' : '') + ';\n';
    code += '   bool sellSignal = ' + this.generateConditionBlock(state.sellConditions, state.sellCombine, 'sell', 'mt4') + (state.useMonthFilter ? ' && !IsMonthFilterActive()' : '') + ';\n\n';

    // Magic Stop Order Check MT4
    if (state.useMagicStopOrder) {
      code += '   //--- マジックストップ（指定金額で新規注文停止） ---\n';
      code += '   double totalFloatingPL = 0;\n';
      code += '   for(int ms = 0; ms < OrdersTotal(); ms++) {\n';
      code += '      if(OrderSelect(ms, SELECT_BY_POS, MODE_TRADES)) {\n';
      code += '         if(OrderSymbol() == Symbol() && OrderMagicNumber() == MagicNumber) {\n';
      code += '            totalFloatingPL += OrderProfit() + OrderSwap() + OrderCommission();\n';
      code += '         }\n';
      code += '      }\n';
      code += '   }\n';
      code += '   if(totalFloatingPL <= -MagicStopAmount || totalFloatingPL >= MagicStopAmount) {\n';
      code += '      if(MagicStopType == 0 || MagicStopType == 1) buySignal = false;\n';
      code += '      if(MagicStopType == 0 || MagicStopType == 2) sellSignal = false;\n';
      code += '   }\n\n';
    }

    // Position mode logic
    const mode = state.positionMode || 'one_direction';
    if (mode === 'one_direction') {
      code += '   //--- 片方向モード（ポジションなし時のみエントリー） ---\n';
      code += '   if(buySignal && buyCount == 0 && sellCount == 0) {\n';
    } else if (mode === 'hedge') {
      code += '   //--- 両建てモード ---\n';
      code += '   if(buySignal && buyCount == 0) {\n';
    } else {
      code += '   if(buySignal && buyCount == 0) {\n';
    }

    // Lot calculation
    code += '      double lot = LotSize;\n';
    if (state.riskPercent > 0) {
      code += '      if(StopLoss > 0) {\n';
      code += '         lot = AccountBalance() * RiskPercent / 100.0 / (StopLoss * MarketInfo(Symbol(), MODE_TICKVALUE));\n';
      code += '         lot = MathMax(MarketInfo(Symbol(), MODE_MINLOT), MathMin(lot, MarketInfo(Symbol(), MODE_MAXLOT)));\n';
      code += '      }\n';
    }

    // Open Buy
    code += '      double sl = 0, tp = 0;\n';
    code += '      if(StopLoss > 0)   sl = Ask - StopLoss * Point;\n';
    code += '      if(TakeProfit > 0)  tp = Ask + TakeProfit * Point;\n';
    code += '      int ticket = OrderSend(Symbol(), OP_BUY, lot, Ask, Slippage, sl, tp, "' + (state.eaName || 'MyEA') + '", MagicNumber, 0, clrBlue);\n';
    code += '      if(ticket < 0) Print("Buy OrderSend error: ", GetLastError());\n';

    if (state.discordNotifyEntry) {
      code += '      else Alert("' + (state.eaName || 'MyEA') + ': Buy order opened");\n';
    }

    code += '   }\n\n';

    // Sell entry
    if (mode === 'one_direction') {
      code += '   if(sellSignal && sellCount == 0 && buyCount == 0) {\n';
    } else if (mode === 'hedge') {
      code += '   if(sellSignal && sellCount == 0) {\n';
    } else {
      code += '   if(sellSignal && sellCount == 0) {\n';
    }

    code += '      double lot2 = LotSize;\n';
    if (state.riskPercent > 0) {
      code += '      if(StopLoss > 0) {\n';
      code += '         lot2 = AccountBalance() * RiskPercent / 100.0 / (StopLoss * MarketInfo(Symbol(), MODE_TICKVALUE));\n';
      code += '         lot2 = MathMax(MarketInfo(Symbol(), MODE_MINLOT), MathMin(lot2, MarketInfo(Symbol(), MODE_MAXLOT)));\n';
      code += '      }\n';
    }

    code += '      double sl2 = 0, tp2 = 0;\n';
    code += '      if(StopLoss > 0)   sl2 = Bid + StopLoss * Point;\n';
    code += '      if(TakeProfit > 0)  tp2 = Bid - TakeProfit * Point;\n';
    code += '      int ticket2 = OrderSend(Symbol(), OP_SELL, lot2, Bid, Slippage, sl2, tp2, "' + (state.eaName || 'MyEA') + '", MagicNumber, 0, clrRed);\n';
    code += '      if(ticket2 < 0) Print("Sell OrderSend error: ", GetLastError());\n';

    if (state.discordNotifyEntry) {
      code += '      else Alert("' + (state.eaName || 'MyEA') + ': Sell order opened");\n';
    }

    code += '   }\n';

    // Strategy calls
    if (state.strategies && state.strategies.includes('nanpin')) {
      code += '\n   //--- ナンピンチェック ---\n';
      code += '   CheckNanpin();\n';
      code += '   CheckNanpinProfit();\n';
    }
    if (state.strategies && state.strategies.includes('martingale')) {
      code += '\n   //--- マーチンゲールチェック ---\n';
      code += '   CheckMartingaleReset();\n';
    }
    if (state.strategies && state.strategies.includes('grid')) {
      code += '\n   //--- グリッドチェック ---\n';
      code += '   CheckGrid();\n';
    }

    // Auto Close by Pips MT4
    if (state.useAutoClose && (state.autoCloseProfitPips > 0 || state.autoCloseLossPips > 0)) {
      code += '\n   //--- Auto Close by Pips\n';
      code += '   for(int i = OrdersTotal() - 1; i >= 0; i--) {\n';
      code += '      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {\n';
      code += '         if(OrderSymbol() == Symbol() && OrderMagicNumber() == MagicNumber) {\n';
      code += '            double currentRate = (OrderType() == OP_BUY) ? Bid : Ask;\n';
      code += '            double profitPips = (OrderType() == OP_BUY) ? (currentRate - OrderOpenPrice()) / Point : (OrderOpenPrice() - currentRate) / Point;\n';
      if (state.autoCloseProfitPips > 0) {
        code += '            if(profitPips >= ' + state.autoCloseProfitPips + ') {\n';
        code += '               if(OrderType() == OP_BUY) OrderClose(OrderTicket(), OrderLots(), Bid, Slippage, clrBlue);\n';
        code += '               if(OrderType() == OP_SELL) OrderClose(OrderTicket(), OrderLots(), Ask, Slippage, clrRed);\n';
        code += '            }\n';
      }
      if (state.autoCloseLossPips > 0) {
        code += '            if(profitPips <= -' + state.autoCloseLossPips + ') {\n';
        code += '               if(OrderType() == OP_BUY) OrderClose(OrderTicket(), OrderLots(), Bid, Slippage, clrBlue);\n';
        code += '               if(OrderType() == OP_SELL) OrderClose(OrderTicket(), OrderLots(), Ask, Slippage, clrRed);\n';
        code += '            }\n';
      }
      code += '         }\n';
      code += '      }\n';
      code += '   }\n';
    }

    // Auto Close by Yen MT4
    if (state.useAutoClose && (state.autoCloseProfitYen > 0 || state.autoCloseLossYen > 0)) {
      code += '\n   //--- Auto Close by Profit/Loss Amount\n';
      code += '   double totalPL = 0;\n';
      code += '   for(int i = 0; i < OrdersTotal(); i++) {\n';
      code += '      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {\n';
      code += '         if(OrderSymbol() == Symbol() && OrderMagicNumber() == MagicNumber) {\n';
      code += '            totalPL += OrderProfit() + OrderSwap() + OrderCommission();\n';
      code += '         }\n';
      code += '      }\n';
      code += '   }\n';
      if (state.autoCloseProfitYen > 0) {
        code += '   if(totalPL >= ' + state.autoCloseProfitYen + ') {\n';
        code += '      CloseAllOrders();\n';
        code += '      Print("Auto close: profit target ' + state.autoCloseProfitYen + ' reached");\n';
        code += '   }\n';
      }
      if (state.autoCloseLossYen > 0) {
        code += '   if(totalPL <= -' + state.autoCloseLossYen + ') {\n';
        code += '      CloseAllOrders();\n';
        code += '      Print("Auto close: loss limit ' + state.autoCloseLossYen + ' reached");\n';
        code += '   }\n';
      }
    }

    code += '}\n\n';
    return code;
  },

  // ==================== [G-041] OnTick MT5 ====================
  generateOnTickMT5: function(state) {
    let code = '//+------------------------------------------------------------------+\n';
    code += '//| Expert tick function                                               |\n';
    code += '//+------------------------------------------------------------------+\n';
    code += 'void OnTick()\n{\n';

    code += '   //--- New bar detection\n';
    code += '   datetime currentBar = iTime(Symbol(), Period(), 0);\n';
    code += '   if(currentBar == lastBarTime) return;\n';
    code += '   lastBarTime = currentBar;\n';
    code += '   barCount++;\n\n';

    if (state.useSpreadFilter) {
      code += '   //--- Spread filter\n';
      code += '   long spread = SymbolInfoInteger(Symbol(), SYMBOL_SPREAD);\n';
      code += '   if(spread > MaxSpread) return;\n\n';
    }

    if (state.entryCooldown > 0) {
      code += '   //--- Entry cooldown\n';
      code += '   if(barCount < EntryCooldown) return;\n\n';
    }

    // Trailing stop
    if (state.useTrailing) {
      code += '   //--- Trailing Stop\n';
      code += '   TrailingStopFunc();\n\n';
    }

    // Auto Close by pips MT5
    if (state.useAutoClose && (state.autoCloseProfitPips > 0 || state.autoCloseLossPips > 0)) {
      code += '   //--- Auto Close by Pips\n';
      code += '   double point = SymbolInfoDouble(Symbol(), SYMBOL_POINT);\n';
      code += '   double bid = SymbolInfoDouble(Symbol(), SYMBOL_BID);\n';
      code += '   double ask = SymbolInfoDouble(Symbol(), SYMBOL_ASK);\n';
      code += '   for(int ac = PositionsTotal() - 1; ac >= 0; ac--) {\n';
      code += '      ulong acTicket = PositionGetTicket(ac);\n';
      code += '      if(PositionGetString(POSITION_SYMBOL) == Symbol() && PositionGetInteger(POSITION_MAGIC) == MagicNumber) {\n';
      code += '         double openP = PositionGetDouble(POSITION_PRICE_OPEN);\n';
      code += '         double profitPips = 0;\n';
      code += '         if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY)  profitPips = (bid - openP) / point;\n';
      code += '         if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_SELL) profitPips = (openP - ask) / point;\n';
      if (state.autoCloseProfitPips > 0) {
        code += '         if(profitPips >= ' + state.autoCloseProfitPips + ') trade.PositionClose(acTicket);\n';
      }
      if (state.autoCloseLossPips > 0) {
        code += '         if(profitPips <= -' + state.autoCloseLossPips + ') trade.PositionClose(acTicket);\n';
      }
      code += '      }\n';
      code += '   }\n\n';
    }

    // Auto Close by Yen MT5
    if (state.useAutoClose && (state.autoCloseProfitYen > 0 || state.autoCloseLossYen > 0)) {
      code += '   //--- Auto Close by Profit/Loss Amount\n';
      code += '   double totalPL = TotalProfit();\n';
      if (state.autoCloseProfitYen > 0) {
        code += '   if(totalPL >= ' + state.autoCloseProfitYen + ') {\n';
        code += '      CloseAllPositions();\n';
        code += '      Print("Auto close: profit target ' + state.autoCloseProfitYen + ' reached");\n';
        code += '   }\n';
      }
      if (state.autoCloseLossYen > 0) {
        code += '   if(totalPL <= -' + state.autoCloseLossYen + ') {\n';
        code += '      CloseAllPositions();\n';
        code += '      Print("Auto close: loss limit ' + state.autoCloseLossYen + ' reached");\n';
        code += '   }\n';
      }
      code += '\n';
    }

    // Indicator-based exit MT5
    if (state.exitConditions && state.exitConditions.length > 0) {
      code += '   //--- Indicator Exit Conditions\n';
      code += '   bool exitSignal = ' + this.generateConditionBlock(state.exitConditions, state.exitCombine, 'buy', 'mt5') + ';\n';
      code += '   if(exitSignal) {\n';
      code += '      CloseAllPositions();\n';
      code += '      Print("Indicator exit triggered");\n';
      code += '   }\n\n';
    }

    // Count positions


    code += '   //--- Count positions\n';
    code += '   int buyCount = 0, sellCount = 0;\n';
    code += '   for(int i = PositionsTotal() - 1; i >= 0; i--) {\n';
    code += '      ulong ticket = PositionGetTicket(i);\n';
    code += '      if(PositionGetString(POSITION_SYMBOL) == Symbol() && PositionGetInteger(POSITION_MAGIC) == MagicNumber) {\n';
    code += '         if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY)  buyCount++;\n';
    code += '         if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_SELL) sellCount++;\n';
    code += '      }\n';
    code += '   }\n\n';

    code += '   //--- Entry Conditions\n';
    code += '   bool buySignal  = ' + this.generateConditionBlock(state.buyConditions, state.buyCombine, 'buy', 'mt5') + (state.useMonthFilter ? ' && !IsMonthFilterActive()' : '') + ';\n';
    code += '   bool sellSignal = ' + this.generateConditionBlock(state.sellConditions, state.sellCombine, 'sell', 'mt5') + (state.useMonthFilter ? ' && !IsMonthFilterActive()' : '') + ';\n\n';

    // Magic Stop Order Check MT5
    if (state.useMagicStopOrder) {
      code += '   //--- マジックストップ（指定金額で新規注文停止） ---\n';
      code += '   double totalFloatingPL = 0;\n';
      code += '   for(int ms = 0; ms < PositionsTotal(); ms++) {\n';
      code += '      ulong msTicket = PositionGetTicket(ms);\n';
      code += '      if(PositionGetString(POSITION_SYMBOL) == Symbol() && PositionGetInteger(POSITION_MAGIC) == MagicNumber) {\n';
      code += '         totalFloatingPL += PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);\n';
      code += '      }\n';
      code += '   }\n';
      code += '   if(totalFloatingPL <= -MagicStopAmount || totalFloatingPL >= MagicStopAmount) {\n';
      code += '      if(MagicStopType == 0 || MagicStopType == 1) buySignal = false;\n';
      code += '      if(MagicStopType == 0 || MagicStopType == 2) sellSignal = false;\n';
      code += '   }\n\n';
    }

    const mode = state.positionMode || 'one_direction';
    if (mode === 'one_direction') {
      code += '   if(buySignal && buyCount == 0 && sellCount == 0) {\n';
    } else {
      code += '   if(buySignal && buyCount == 0) {\n';
    }

    code += '      double lot = LotSize;\n';
    code += '      double ask = SymbolInfoDouble(Symbol(), SYMBOL_ASK);\n';
    code += '      double sl = 0, tp = 0;\n';
    code += '      double point = SymbolInfoDouble(Symbol(), SYMBOL_POINT);\n';
    code += '      if(StopLoss > 0)   sl = ask - StopLoss * point;\n';
    code += '      if(TakeProfit > 0)  tp = ask + TakeProfit * point;\n';
    code += '      trade.Buy(lot, Symbol(), ask, sl, tp, "' + (state.eaName || 'MyEA') + '");\n';
    code += '   }\n\n';

    if (mode === 'one_direction') {
      code += '   if(sellSignal && sellCount == 0 && buyCount == 0) {\n';
    } else {
      code += '   if(sellSignal && sellCount == 0) {\n';
    }

    code += '      double lot2 = LotSize;\n';
    code += '      double bid = SymbolInfoDouble(Symbol(), SYMBOL_BID);\n';
    code += '      double sl2 = 0, tp2 = 0;\n';
    code += '      double point2 = SymbolInfoDouble(Symbol(), SYMBOL_POINT);\n';
    code += '      if(StopLoss > 0)   sl2 = bid + StopLoss * point2;\n';
    code += '      if(TakeProfit > 0)  tp2 = bid - TakeProfit * point2;\n';
    code += '      trade.Sell(lot2, Symbol(), bid, sl2, tp2, "' + (state.eaName || 'MyEA') + '");\n';
    code += '   }\n';

    // Strategy calls
    if (state.strategies && state.strategies.includes('nanpin')) {
      code += '\n   //--- Nanpin check\n';
      code += '   CheckNanpin();\n';
      code += '   CheckNanpinProfit();\n';
    }
    if (state.strategies && state.strategies.includes('martingale')) {
      code += '\n   //--- Martingale check\n';
      code += '   CheckMartingaleReset();\n';
    }
    if (state.strategies && state.strategies.includes('grid')) {
      code += '\n   //--- Grid check\n';
      code += '   CheckGrid();\n';
    }

    // Auto close by profit/loss
    if (state.autoCloseProfit > 0) {
      code += '\n   //--- Auto close by profit\n';
      code += '   if(TotalProfit() >= ' + state.autoCloseProfit + ') {\n';
      code += '      CloseAllPositions();\n';
      if (state.alertOnExit) code += '      SendAlert("Auto close: profit target reached");\n';
      code += '   }\n';
    }
    if (state.autoCloseLoss > 0) {
      code += '\n   //--- Auto close by loss\n';
      code += '   if(TotalProfit() <= -' + state.autoCloseLoss + ') {\n';
      code += '      CloseAllPositions();\n';
      if (state.alertOnExit) code += '      SendAlert("Auto close: loss limit reached");\n';
      code += '   }\n';
    }

    code += '}\n\n';
    return code;
  },


  // ==================== [G-050] Condition Block Generator ====================
  generateConditionBlock: function(conditions, combine, direction, platform) {
    if (!conditions || conditions.length === 0) {
      return 'true';
    }

    const parts = conditions.map((c, idx) => {
      return this.generateSingleCondition(c, direction, platform, idx);
    });

    const joiner = (combine === 'OR' || combine === 'or') ? ' || ' : ' && ';
    return '(' + parts.join(joiner) + ')';
  },

  generateSingleCondition: function(condition, direction, platform, idx) {
    const cat = condition.category || 'indicator';
    // The wizard stores the indicator name in condition.indicator or condition.detail (as string)
    // and the parameters in condition.params (as object)
    const ind = condition.indicator || condition.id || (typeof condition.detail === 'string' ? condition.detail : '') || 'ma';
    
    // Merge params + shift + conditionType into a detail object for the generator
    const detail = {
      ...(condition.params || {}),
      shift: parseInt(condition.shift) || 1,
      conditionType: condition.conditionType || condition.type || ''
    };
    // If condition.detail is an object (legacy format), merge it too
    if (typeof condition.detail === 'object' && condition.detail !== null) {
      Object.assign(detail, condition.detail);
    }

    if (cat === 'indicator') {
      return this.generateIndicatorCondition(ind, direction, platform, detail, idx);
    } else if (cat === 'candle') {
      return this.generateCandleCondition(ind, direction, platform, detail, idx);
    } else if (cat === 'price') {
      return this.generatePriceCondition(ind, direction, platform, detail, idx);
    }
    return 'true';
  },

  // ==================== [G-060] Indicator Conditions ====================
  generateIndicatorCondition: function(ind, direction, platform, detail, idx) {
    const shift = detail.shift || 1;
    const isBuy = (direction === 'buy');

    switch(ind) {
      case 'ma':
      case 'moving_average': {
        const fast = detail.fastPeriod || 20;
        const slow = detail.slowPeriod || 50;
        const method = detail.method || 'MODE_SMA';
        if (platform === 'mt4') {
          const fma = `iMA(Symbol(),Period(),${fast},0,${method},PRICE_CLOSE,${shift})`;
          const sma = `iMA(Symbol(),Period(),${slow},0,${method},PRICE_CLOSE,${shift})`;
          const fma1 = `iMA(Symbol(),Period(),${fast},0,${method},PRICE_CLOSE,${shift + 1})`;
          const sma1 = `iMA(Symbol(),Period(),${slow},0,${method},PRICE_CLOSE,${shift + 1})`;
          if (isBuy) return `(${fma} > ${sma} && ${fma1} <= ${sma1})`;
          else       return `(${fma} < ${sma} && ${fma1} >= ${sma1})`;
        } else {
          return isBuy ? `CheckMACross_Buy_${idx}()` : `CheckMACross_Sell_${idx}()`;
        }
      }

      case 'rsi': {
        const period = detail.period || 14;
        const overbought = detail.overbought || 70;
        const oversold = detail.oversold || 30;
        if (platform === 'mt4') {
          const rsi = `iRSI(Symbol(),Period(),${period},PRICE_CLOSE,${shift})`;
          if (isBuy) return `(${rsi} < ${oversold})`;
          else       return `(${rsi} > ${overbought})`;
        } else {
          return isBuy ? `CheckRSI_Buy_${idx}()` : `CheckRSI_Sell_${idx}()`;
        }
      }

      case 'macd': {
        const fast = detail.fastPeriod || 12;
        const slow = detail.slowPeriod || 26;
        const signal = detail.signalPeriod || 9;
        if (platform === 'mt4') {
          const main0 = `iMACD(Symbol(),Period(),${fast},${slow},${signal},PRICE_CLOSE,MODE_MAIN,${shift})`;
          const sig0  = `iMACD(Symbol(),Period(),${fast},${slow},${signal},PRICE_CLOSE,MODE_SIGNAL,${shift})`;
          const main1 = `iMACD(Symbol(),Period(),${fast},${slow},${signal},PRICE_CLOSE,MODE_MAIN,${shift + 1})`;
          const sig1  = `iMACD(Symbol(),Period(),${fast},${slow},${signal},PRICE_CLOSE,MODE_SIGNAL,${shift + 1})`;
          if (isBuy) return `(${main0} > ${sig0} && ${main1} <= ${sig1})`;
          else       return `(${main0} < ${sig0} && ${main1} >= ${sig1})`;
        } else {
          return isBuy ? `CheckMACD_Buy_${idx}()` : `CheckMACD_Sell_${idx}()`;
        }
      }

      case 'bollinger': {
        const period = detail.period || 20;
        const dev = detail.deviation || 2.0;
        if (platform === 'mt4') {
          const upper = `iBands(Symbol(),Period(),${period},${dev},0,PRICE_CLOSE,MODE_UPPER,${shift})`;
          const lower = `iBands(Symbol(),Period(),${period},${dev},0,PRICE_CLOSE,MODE_LOWER,${shift})`;
          if (isBuy) return `(${this._close(shift)} < ${lower})`;
          else       return `(${this._close(shift)} > ${upper})`;
        } else {
          return isBuy ? `CheckBB_Buy_${idx}()` : `CheckBB_Sell_${idx}()`;
        }
      }

        case 'stochastic': {
        const k = detail.kPeriod || detail.stoch_k || (detail.params && detail.params.stoch_k) || 5;
        const d = detail.dPeriod || detail.stoch_d || (detail.params && detail.params.stoch_d) || 3;
        const slowing = detail.slowing || detail.stoch_slowing || (detail.params && detail.params.stoch_slowing) || 3;
        const lv = detail.level || detail.stoch_level || (detail.params && detail.params.level) || 20;
        const type = detail.type || detail.conditionType || '';

        if (platform === 'mt4') {
          const main0 = `iStochastic(Symbol(),Period(),${k},${d},${slowing},MODE_SMA,0,MODE_MAIN,${shift})`;
          const main1 = `iStochastic(Symbol(),Period(),${k},${d},${slowing},MODE_SMA,0,MODE_MAIN,${shift + 1})`;
          const sig0  = `iStochastic(Symbol(),Period(),${k},${d},${slowing},MODE_SMA,0,MODE_SIGNAL,${shift})`;
          const sig1  = `iStochastic(Symbol(),Period(),${k},${d},${slowing},MODE_SMA,0,MODE_SIGNAL,${shift + 1})`;

          if (type === 'cross_up')   return `(${main0} > ${sig0} && ${main1} <= ${sig1})`;
          if (type === 'cross_down') return `(${main0} < ${sig0} && ${main1} >= ${sig1})`;
          if (type === 'above_level' || type === 'overbought') return `(${main0} > ${lv})`;
          if (type === 'below_level' || type === 'oversold')   return `(${main0} < ${lv})`;
          
          if (!type || type === '') {
            if (isBuy) return `(${main0} < 20)`;
            else       return `(${main0} > 80)`;
          }
          return 'true';
        } else {
          return isBuy ? `CheckStoch_Buy_${idx}()` : `CheckStoch_Sell_${idx}()`;
        }
      }

      case 'cci': {
        const period = detail.period || 14;
        const ob = detail.overbought || 100;
        const os = detail.oversold || -100;
        if (platform === 'mt4') {
          const cci = `iCCI(Symbol(),Period(),${period},PRICE_TYPICAL,${shift})`;
          if (isBuy) return `(${cci} < ${os})`;
          else       return `(${cci} > ${ob})`;
        } else {
          return isBuy ? `CheckCCI_Buy_${idx}()` : `CheckCCI_Sell_${idx}()`;
        }
      }

      case 'adx': {
        const period = detail.period || 14;
        const level = detail.level || 25;
        const type = detail.type || detail.conditionType;
        if (platform === 'mt4') {
          const plusDI  = `iADX(Symbol(),Period(),${period},PRICE_CLOSE,MODE_PLUSDI,${shift})`;
          const minusDI = `iADX(Symbol(),Period(),${period},PRICE_CLOSE,MODE_MINUSDI,${shift})`;
          const adxMain = `iADX(Symbol(),Period(),${period},PRICE_CLOSE,MODE_MAIN,${shift})`;
          if (type === 'plus_above_minus' || (isBuy && !type)) return `(${plusDI} > ${minusDI})`;
          if (type === 'minus_above_plus' || (!isBuy && !type)) return `(${minusDI} > ${plusDI})`;
          if (isBuy) return `(${adxMain} > ${level} && ${plusDI} > ${minusDI})`;
          else       return `(${adxMain} > ${level} && ${minusDI} > ${plusDI})`;
        } else {
          return isBuy ? `CheckADX_Buy_${idx}()` : `CheckADX_Sell_${idx}()`;
        }
      }
      case 'atr': {
        const period = detail.period || 14;
        const level = detail.level || 20;
        const type = detail.type || detail.conditionType;
        if (platform === 'mt4') {
          const atr = `iATR(Symbol(),Period(),${period},${shift})`;
          if (type === 'below' || type === 'below_level') {
            return `(${atr} < ${level} * Point)`;
          }
          return `(${atr} > ${level} * Point)`;
        } else {
          return isBuy ? `CheckATR_Buy_${idx}()` : `CheckATR_Sell_${idx}()`;
        }
      }

      case 'ichimoku': {
        const p = detail.params || {};
        const tenkan = detail.tenkan || p.tenkan || 9;
        const kijun = detail.kijun || p.kijun || 26;
        const senkou = detail.senkou || p.senkou || 52;
        if (platform === 'mt4') {
          const tenkanLine = `iIchimoku(Symbol(),Period(),${tenkan},${kijun},${senkou},MODE_TENKANSEN,${shift})`;
          const kijunLine = `iIchimoku(Symbol(),Period(),${tenkan},${kijun},${senkou},MODE_KIJUNSEN,${shift})`;
          const spanA = `iIchimoku(Symbol(),Period(),${tenkan},${kijun},${senkou},MODE_SENKOUSPANA,${shift})`;
          const spanB = `iIchimoku(Symbol(),Period(),${tenkan},${kijun},${senkou},MODE_SENKOUSPANB,${shift})`;
          const tenkanPrev = `iIchimoku(Symbol(),Period(),${tenkan},${kijun},${senkou},MODE_TENKANSEN,${shift + 1})`;
          const kijunPrev = `iIchimoku(Symbol(),Period(),${tenkan},${kijun},${senkou},MODE_KIJUNSEN,${shift + 1})`;
          const close = this._close(shift);

          const condType = detail.type || detail.conditionType || 'kumo_break';
          if (condType === 'tenkan_kijun') {
            if (isBuy) return `(${tenkanLine} > ${kijunLine} && ${tenkanPrev} <= ${kijunPrev})`;
            else       return `(${tenkanLine} < ${kijunLine} && ${tenkanPrev} >= ${kijunPrev})`;
          } else if (condType === 'above_kumo') {
            if (isBuy) return `(${close} > MathMax(${spanA},${spanB}))`;
            else       return `(${close} < MathMin(${spanA},${spanB}))`;
          } else if (condType === 'below_kumo') {
            if (isBuy) return `(${close} < MathMin(${spanA},${spanB}))`;
            else       return `(${close} > MathMax(${spanA},${spanB}))`;
          } else {
            // kumo_break
            const closePrev = this._close(shift + 1);
            const spanAPrev = `iIchimoku(Symbol(),Period(),${tenkan},${kijun},${senkou},MODE_SENKOUSPANA,${shift + 1})`;
            const spanBPrev = `iIchimoku(Symbol(),Period(),${tenkan},${kijun},${senkou},MODE_SENKOUSPANB,${shift + 1})`;
            if (isBuy) return `(${close} > MathMax(${spanA},${spanB}) && ${closePrev} <= MathMax(${spanAPrev},${spanBPrev}))`;
            else       return `(${close} < MathMin(${spanA},${spanB}) && ${closePrev} >= MathMin(${spanAPrev},${spanBPrev}))`;
          }
        } else {
          return isBuy ? `CheckIchimoku_Buy_${idx}()` : `CheckIchimoku_Sell_${idx}()`;
        }
      }

      case 'envelope': {
        const period = detail.period || 14;
        const deviation = detail.deviation || 0.1;
        if (platform === 'mt4') {
          const upper = `iEnvelopes(Symbol(),Period(),${period},MODE_SMA,0,PRICE_CLOSE,${deviation},MODE_UPPER,${shift})`;
          const lower = `iEnvelopes(Symbol(),Period(),${period},MODE_SMA,0,PRICE_CLOSE,${deviation},MODE_LOWER,${shift})`;
          if (isBuy) return `(${this._close(shift)} < ${lower})`;
          else       return `(${this._close(shift)} > ${upper})`;
        } else {
          return isBuy ? `CheckEnvelope_Buy_${idx}()` : `CheckEnvelope_Sell_${idx}()`;
        }
      }

      case 'parabolic': {
        const step = detail.step || 0.02;
        const max = detail.max || 0.2;
        if (platform === 'mt4') {
          const sar = `iSAR(Symbol(),Period(),${step},${max},${shift})`;
          const sarPrev = `iSAR(Symbol(),Period(),${step},${max},${shift + 1})`;
          const close = this._close(shift);
          const closePrev = this._close(shift + 1);
          if (isBuy) return `(${close} > ${sar} && ${closePrev} <= ${sarPrev})`;
          else       return `(${close} < ${sar} && ${closePrev} >= ${sarPrev})`;
        } else {
          return isBuy ? `CheckSAR_Buy_${idx}()` : `CheckSAR_Sell_${idx}()`;
        }
      }

      case 'williams': {
        const period = detail.period || 14;
        const ob = detail.overbought || -20;
        const os = detail.oversold || -80;
        if (platform === 'mt4') {
          const wr = `iWPR(Symbol(),Period(),${period},${shift})`;
          if (isBuy) return `(${wr} < ${os})`;
          else       return `(${wr} > ${ob})`;
        } else {
          return isBuy ? `CheckWPR_Buy_${idx}()` : `CheckWPR_Sell_${idx}()`;
        }
      }

      case 'demarker': {
        const period = detail.period || 14;
        if (platform === 'mt4') {
          const dm = `iDeMarker(Symbol(),Period(),${period},${shift})`;
          if (isBuy) return `(${dm} < 0.3)`;
          else       return `(${dm} > 0.7)`;
        } else {
          return isBuy ? `CheckDeMarker_Buy_${idx}()` : `CheckDeMarker_Sell_${idx}()`;
        }
      }

      case 'momentum': {
        const period = detail.period || 14;
        if (platform === 'mt4') {
          const mom = `iMomentum(Symbol(),Period(),${period},PRICE_CLOSE,${shift})`;
          const momPrev = `iMomentum(Symbol(),Period(),${period},PRICE_CLOSE,${shift + 1})`;
          if (isBuy) return `(${mom} > 100 && ${momPrev} <= 100)`;
          else       return `(${mom} < 100 && ${momPrev} >= 100)`;
        } else {
          return isBuy ? `CheckMomentum_Buy_${idx}()` : `CheckMomentum_Sell_${idx}()`;
        }
      }

      case 'osma': {
        const fast = detail.fastPeriod || 12;
        const slow = detail.slowPeriod || 26;
        const signal = detail.signalPeriod || 9;
        if (platform === 'mt4') {
          const osma = `iOsMA(Symbol(),Period(),${fast},${slow},${signal},PRICE_CLOSE,${shift})`;
          const osmaPrev = `iOsMA(Symbol(),Period(),${fast},${slow},${signal},PRICE_CLOSE,${shift + 1})`;
          if (isBuy) return `(${osma} > 0 && ${osmaPrev} <= 0)`;
          else       return `(${osma} < 0 && ${osmaPrev} >= 0)`;
        } else {
          return isBuy ? `CheckOsMA_Buy_${idx}()` : `CheckOsMA_Sell_${idx}()`;
        }
      }

      case 'ao': {
        if (platform === 'mt4') {
          const ao = `iAO(Symbol(),Period(),${shift})`;
          const aoPrev = `iAO(Symbol(),Period(),${shift + 1})`;
          if (isBuy) return `(${ao} > 0 && ${aoPrev} <= 0)`;
          else       return `(${ao} < 0 && ${aoPrev} >= 0)`;
        } else {
          return isBuy ? `CheckAO_Buy_${idx}()` : `CheckAO_Sell_${idx}()`;
        }
      }

      case 'ac': {
        if (platform === 'mt4') {
          const ac = `iAC(Symbol(),Period(),${shift})`;
          const acPrev = `iAC(Symbol(),Period(),${shift + 1})`;
          if (isBuy) return `(${ac} > 0 && ${acPrev} <= 0)`;
          else       return `(${ac} < 0 && ${acPrev} >= 0)`;
        } else {
          return isBuy ? `CheckAC_Buy_${idx}()` : `CheckAC_Sell_${idx}()`;
        }
      }

      case 'rvi': {
        const period = detail.period || 10;
        if (platform === 'mt4') {
          const main = `iRVI(Symbol(),Period(),${period},MODE_MAIN,${shift})`;
          const sig = `iRVI(Symbol(),Period(),${period},MODE_SIGNAL,${shift})`;
          const mainPrev = `iRVI(Symbol(),Period(),${period},MODE_MAIN,${shift + 1})`;
          const sigPrev = `iRVI(Symbol(),Period(),${period},MODE_SIGNAL,${shift + 1})`;
          if (isBuy) return `(${main} > ${sig} && ${mainPrev} <= ${sigPrev})`;
          else       return `(${main} < ${sig} && ${mainPrev} >= ${sigPrev})`;
        } else {
          return isBuy ? `CheckRVI_Buy_${idx}()` : `CheckRVI_Sell_${idx}()`;
        }
      }

      case 'bears': {
        const period = detail.period || 13;
        if (platform === 'mt4') {
          const bears = `iBearsPower(Symbol(),Period(),${period},PRICE_CLOSE,${shift})`;
          if (isBuy) return `(${bears} < 0)`;
          else       return `(${bears} > 0)`;
        } else {
          return isBuy ? `CheckBears_Buy_${idx}()` : `CheckBears_Sell_${idx}()`;
        }
      }

      case 'bulls': {
        const period = detail.period || 13;
        if (platform === 'mt4') {
          const bulls = `iBullsPower(Symbol(),Period(),${period},PRICE_CLOSE,${shift})`;
          if (isBuy) return `(${bulls} > 0)`;
          else       return `(${bulls} < 0)`;
        } else {
          return isBuy ? `CheckBulls_Buy_${idx}()` : `CheckBulls_Sell_${idx}()`;
        }
      }

      case 'pivot': {
        if (platform === 'mt4') {
          const pH = `iHigh(Symbol(),PERIOD_D1,1)`;
          const pL = `iLow(Symbol(),PERIOD_D1,1)`;
          const pC = `iClose(Symbol(),PERIOD_D1,1)`;
          const pivot = `((${pH}+${pL}+${pC})/3.0)`;
          const r1 = `(2.0*${pivot}-${pL})`;
          const s1 = `(2.0*${pivot}-${pH})`;
          const close = this._close(shift);
          if (isBuy) return `(${close} > ${pivot})`;
          else       return `(${close} < ${pivot})`;
        } else {
          return isBuy ? `CheckPivot_Buy_${idx}()` : `CheckPivot_Sell_${idx}()`;
        }
      }

      case 'fibonacci': {
        const lookback = detail.lookback || 50;
        if (platform === 'mt4') {
          const close = this._close(shift);
          const hh = `iHigh(Symbol(),Period(),iHighest(Symbol(),Period(),MODE_HIGH,${lookback},1))`;
          const ll = `iLow(Symbol(),Period(),iLowest(Symbol(),Period(),MODE_LOW,${lookback},1))`;
          const fib382 = `(${ll}+(${hh}-${ll})*0.382)`;
          const fib618 = `(${ll}+(${hh}-${ll})*0.618)`;
          if (isBuy) return `(${close} > ${fib382} && ${close} < ${fib618})`;
          else       return `(${close} < ${fib618} && ${close} > ${fib382})`;
        } else {
          return isBuy ? `CheckFib_Buy_${idx}()` : `CheckFib_Sell_${idx}()`;
        }
      }

      case 'heiken_ashi': {
        const cond = detail.type || detail.conditionType;
        if (platform === 'mt4') {
          const haOpen = `iCustom(Symbol(),Period(),"Heiken Ashi",0,${shift})`;
          const haClose = `iCustom(Symbol(),Period(),"Heiken Ashi",3,${shift})`;
          switch(cond) {
            case 'bullish': return `(${haClose} > ${haOpen})`;
            case 'bearish': return `(${haClose} < ${haOpen})`;
            case 'turn_up': return `(${haClose} > ${haOpen} && iCustom(Symbol(),Period(),"Heiken Ashi",3,${shift+1}) < iCustom(Symbol(),Period(),"Heiken Ashi",0,${shift+1}))`;
            case 'turn_down': return `(${haClose} < ${haOpen} && iCustom(Symbol(),Period(),"Heiken Ashi",3,${shift+1}) > iCustom(Symbol(),Period(),"Heiken Ashi",0,${shift+1}))`;
          }
        } else {
          return isBuy ? `CheckHA_Buy_${idx}()` : `CheckHA_Sell_${idx}()`;
        }
      }

      case 'ma_cross': {
        const fast = detail.fastPeriod || 5;
        const slow = detail.slowPeriod || 20;
        const method = detail.method || 0;
        const cond = detail.type || detail.conditionType;
        if (platform === 'mt4') {
          const f0 = `iMA(Symbol(),Period(),${fast},0,${method},PRICE_CLOSE,${shift})`;
          const f1 = `iMA(Symbol(),Period(),${fast},0,${method},PRICE_CLOSE,${shift+1})`;
          const s0 = `iMA(Symbol(),Period(),${slow},0,${method},PRICE_CLOSE,${shift})`;
          const s1 = `iMA(Symbol(),Period(),${slow},0,${method},PRICE_CLOSE,${shift+1})`;
          if (cond === 'golden_cross') return `(${f0} > ${s0} && ${f1} <= ${s1})`;
          if (cond === 'dead_cross')   return `(${f0} < ${s0} && ${f1} >= ${s1})`;
        } else {
          return isBuy ? `CheckMACross_Buy_${idx}()` : `CheckMACross_Sell_${idx}()`;
        }
      }

      case 'ma_perfect': {
        const p1 = detail.shortPeriod || 10;
        const p2 = detail.midPeriod || 25;
        const p3 = detail.longPeriod || 50;
        const m = detail.method || 0;
        const cond = detail.type || detail.conditionType;
        if (platform === 'mt4') {
          const ma1 = `iMA(Symbol(),Period(),${p1},0,${m},PRICE_CLOSE,${shift})`;
          const ma2 = `iMA(Symbol(),Period(),${p2},0,${m},PRICE_CLOSE,${shift})`;
          const ma3 = `iMA(Symbol(),Period(),${p3},0,${m},PRICE_CLOSE,${shift})`;
          if (cond === 'bullish') return `(${ma1} > ${ma2} && ${ma2} > ${ma3})`;
          if (cond === 'bearish') return `(${ma1} < ${ma2} && ${ma2} < ${ma3})`;
        } else {
          return isBuy ? `CheckMAPerfect_Buy_${idx}()` : `CheckMAPerfect_Sell_${idx}()`;
        }
      }

      case 'ma_deviation': {
        const period = detail.period || 20;
        const thresh = detail.threshold || 30;
        const m = detail.method || 0;
        const cond = detail.type || detail.conditionType;
        if (platform === 'mt4') {
          const ma = `iMA(Symbol(),Period(),${period},0,${m},PRICE_CLOSE,${shift})`;
          const close = this._close(shift);
          const dev = `((${close} - ${ma}) / Point / 10.0)`;
          if (cond === 'above_pips') return `(${dev} > ${thresh})`;
          if (cond === 'below_pips') return `(${dev} < -${thresh})`;
        } else {
          return isBuy ? `CheckMADev_Buy_${idx}()` : `CheckMADev_Sell_${idx}()`;
        }
      }

      case 'round_numbers': {
        const distance = detail.distance || 5;
        const step = detail.step || 100;
        const cond = detail.type || detail.conditionType;
        if (platform === 'mt4') {
          const close = this._close(shift);
          const level = `(MathRound(${close} / (${step} * 10 * Point)) * (${step} * 10 * Point))`;
          if (cond === 'near_level') return `(MathAbs(${close} - ${level}) < ${distance} * 10 * Point)`;
          if (cond === 'cross_up') {
              const c1 = this._close(shift + 1);
              return `(${close} > ${level} && ${c1} <= ${level})`;
          }
        } else {
          return isBuy ? `CheckRound_Buy_${idx}()` : `CheckRound_Sell_${idx}()`;
        }
      }

      case 'holiday_filter': {
          return `!IsHoliday()`;
      }

      default:
        return 'true';
    }
  },

  // ==================== [G-070] Candle Conditions ====================
  generateCandleCondition: function(ind, direction, platform, detail, idx) {
    const shift = detail.shift || 1;
    const isBuy = (direction === 'buy');

    if (platform === 'mt4') {
      const o = this._open(shift);
      const c = this._close(shift);
      const h = this._high(shift);
      const l = this._low(shift);

      switch(ind) {
        case 'bullish':
          return isBuy ? `(${c} > ${o})` : `(${c} < ${o})`;
        case 'bearish':
          return isBuy ? `(${c} < ${o})` : `(${c} > ${o})`;
        case 'doji':
          return `(MathAbs(${c} - ${o}) < (${h} - ${l}) * 0.1)`;
        case 'engulfing_bull': {
          const o1 = this._open(shift + 1);
          const c1 = this._close(shift + 1);
          if (isBuy) return `(${c} > ${o} && ${c1} < ${o1} && ${c} > ${o1} && ${o} < ${c1})`;
          else       return `(${c} < ${o} && ${c1} > ${o1} && ${c} < ${o1} && ${o} > ${c1})`;
        }
        case 'engulfing_bear': {
          const o1 = this._open(shift + 1);
          const c1 = this._close(shift + 1);
          if (isBuy) return `(${c} < ${o} && ${c1} > ${o1} && ${c} < ${o1} && ${o} > ${c1})`;
          else       return `(${c} > ${o} && ${c1} < ${o1} && ${c} > ${o1} && ${o} < ${c1})`;
        }
        case 'pinbar_bull':
          return isBuy
            ? `((${h} - MathMax(${o},${c})) < (MathAbs(${c}-${o})*0.3) && (MathMin(${o},${c}) - ${l}) > (MathAbs(${c}-${o})*2.0))`
            : `((MathMin(${o},${c}) - ${l}) < (MathAbs(${c}-${o})*0.3) && (${h} - MathMax(${o},${c})) > (MathAbs(${c}-${o})*2.0))`;
        case 'pinbar_bear':
          return isBuy
            ? `((MathMin(${o},${c}) - ${l}) < (MathAbs(${c}-${o})*0.3) && (${h} - MathMax(${o},${c})) > (MathAbs(${c}-${o})*2.0))`
            : `((${h} - MathMax(${o},${c})) < (MathAbs(${c}-${o})*0.3) && (MathMin(${o},${c}) - ${l}) > (MathAbs(${c}-${o})*2.0))`;
        case 'body_size':
          return `(MathAbs(${c} - ${o}) > ${detail.minSize || 10} * Point)`;
        case 'upper_wick':
          return `((${h} - MathMax(${o},${c})) > ${detail.minSize || 10} * Point)`;
        case 'lower_wick':
          return `((MathMin(${o},${c}) - ${l}) > ${detail.minSize || 10} * Point)`;
        default:
          return 'true';
      }
    }
    return 'true';
  },

  // ==================== [G-080] Price Conditions ====================
  generatePriceCondition: function(ind, direction, platform, detail, idx) {
    const shift = detail.shift || 1;
    const price = detail.price || 0;

    if (platform === 'mt4') {
      switch(ind) {
        case 'price_above':
          return `(${this._close(shift)} > ${price})`;
        case 'price_below':
          return `(${this._close(shift)} < ${price})`;
        case 'price_cross_up':
          return `(${this._close(shift)} > ${price} && ${this._close(shift + 1)} <= ${price})`;
        case 'price_cross_dn':
          return `(${this._close(shift)} < ${price} && ${this._close(shift + 1)} >= ${price})`;
        default:
          return 'true';
      }
    }
    return 'true';
  },

  // ==================== [G-090] Helper Functions MT4 ====================
  generateHelperFunctionsMT4: function(state) {
    let code = '';

    // Trailing Stop
    if (state.useTrailing) {
      code += '//+------------------------------------------------------------------+\n';
      code += '//| Trailing Stop Function                                            |\n';
      code += '//+------------------------------------------------------------------+\n';
      code += 'void TrailingStopFunc()\n{\n';
      code += '   for(int i = OrdersTotal() - 1; i >= 0; i--) {\n';
      code += '      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {\n';
      code += '         if(OrderSymbol() == Symbol() && OrderMagicNumber() == MagicNumber) {\n';
      code += '            if(OrderType() == OP_BUY) {\n';
      code += '               if(Bid - OrderOpenPrice() >= TrailingStart * Point) {\n';
      code += '                  double newSL = Bid - TrailingWidth * Point;\n';
      code += '                  if(OrderStopLoss() == 0 || newSL - OrderStopLoss() >= TrailingStep * Point) {\n';
      code += '                     OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrBlue);\n';
      code += '                  }\n';
      code += '               }\n';
      code += '            }\n';
      code += '            if(OrderType() == OP_SELL) {\n';
      code += '               if(OrderOpenPrice() - Ask >= TrailingStart * Point) {\n';
      code += '                  double newSL = Ask + TrailingWidth * Point;\n';
      code += '                  if(OrderStopLoss() == 0 || OrderStopLoss() - newSL >= TrailingStep * Point) {\n';
      code += '                     OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrRed);\n';
      code += '                  }\n';
      code += '               }\n';
      code += '            }\n';
      code += '         }\n';
      code += '      }\n';
      code += '   }\n';
      code += '}\n\n';
    }

    // Close All Orders
    code += '//+------------------------------------------------------------------+\n';
    code += '//| Close All Orders                                                  |\n';
    code += '//+------------------------------------------------------------------+\n';
    code += 'void CloseAllOrders(int type = -1)\n{\n';
    code += '   for(int i = OrdersTotal() - 1; i >= 0; i--) {\n';
    code += '      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {\n';
    code += '         if(OrderSymbol() == Symbol() && OrderMagicNumber() == MagicNumber) {\n';
    code += '            if(type == -1 || OrderType() == type) {\n';
    code += '               if(OrderType() == OP_BUY)  OrderClose(OrderTicket(), OrderLots(), Bid, Slippage, clrBlue);\n';
    code += '               if(OrderType() == OP_SELL) OrderClose(OrderTicket(), OrderLots(), Ask, Slippage, clrRed);\n';
    code += '            }\n';
    code += '         }\n';
    code += '      }\n';
    code += '   }\n';
    code += '}\n\n';

    // Count Orders
    code += 'int CountOrders(int type = -1)\n{\n';
    code += '   int count = 0;\n';
    code += '   for(int i = OrdersTotal() - 1; i >= 0; i--) {\n';
    code += '      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {\n';
    code += '         if(OrderSymbol() == Symbol() && OrderMagicNumber() == MagicNumber) {\n';
    code += '            if(type == -1 || OrderType() == type) count++;\n';
    code += '         }\n';
    code += '      }\n';
    code += '   }\n';
    code += '   return count;\n';
    code += '}\n\n';

    // Total Profit
    code += 'double TotalProfit(int type = -1)\n{\n';
    code += '   double profit = 0;\n';
    code += '   for(int i = OrdersTotal() - 1; i >= 0; i--) {\n';
    code += '      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {\n';
    code += '         if(OrderSymbol() == Symbol() && OrderMagicNumber() == MagicNumber) {\n';
    code += '            if(type == -1 || OrderType() == type) profit += OrderProfit() + OrderSwap() + OrderCommission();\n';
    code += '         }\n';
    code += '      }\n';
    code += '   }\n';
    code += '   return profit;\n';
    code += '}\n\n';

    // Last Order Price
    code += 'double LastOrderPrice(int type)\n{\n';
    code += '   datetime lastTime = 0;\n';
    code += '   double lastPrice = 0;\n';
    code += '   for(int i = OrdersTotal() - 1; i >= 0; i--) {\n';
    code += '      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {\n';
    code += '         if(OrderSymbol() == Symbol() && OrderMagicNumber() == MagicNumber && OrderType() == type) {\n';
    code += '            if(OrderOpenTime() > lastTime) {\n';
    code += '               lastTime = OrderOpenTime();\n';
    code += '               lastPrice = OrderOpenPrice();\n';
    code += '            }\n';
    code += '         }\n';
    code += '      }\n';
    code += '   }\n';
    code += '   return lastPrice;\n';
    code += '}\n\n';

    // Helper: Month Filter
    code += '//+------------------------------------------------------------------+\n';
    code += '//| Month-end/Month-start Filter                                     |\n';
    code += '//+------------------------------------------------------------------+\n';
    code += 'bool IsMonthFilterActive()\n{\n';
    code += '   if(!UseMonthFilter) return false;\n';
    code += '   int day = TimeDay(TimeCurrent());\n';
    code += '   if(day <= MonthStartDays) return true;\n';
    code += '   for(int i = 1; i <= MonthEndDays; i++) {\n';
    code += '      datetime future = TimeCurrent() + 86400 * i;\n';
    code += '      if(TimeMonth(future) != TimeMonth(TimeCurrent())) return true;\n';
    code += '   }\n';
    code += '   return false;\n';
    code += '}\n\n';

    // Helper: Nanpin Profit
    code += 'void CheckNanpinProfit()\n{\n';
    code += '   if(NanpinTargetProfit <= 0) return;\n';
    code += '   double totalProfit = 0;\n';
    code += '   int count = 0;\n';
    code += '   for(int i = OrdersTotal() - 1; i >= 0; i--) {\n';
    code += '      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {\n';
    code += '         if(OrderSymbol() == Symbol() && OrderMagicNumber() == MagicNumber) {\n';
    code += '            totalProfit += OrderProfit() + OrderSwap() + OrderCommission();\n';
    code += '            count++;\n';
    code += '         }\n';
    code += '      }\n';
    code += '   }\n';
    code += '   if(count > 0 && totalProfit >= NanpinTargetProfit) {\n';
    code += '      CloseAllOrders();\n';
    code += '   }\n';
    code += '}\n\n';

    // IsNewsTime (Simplified Auto-News)
    if (state.useNewsFilter) {
      code += '//+------------------------------------------------------------------+\n';
      code += '//| IsNewsTime (Wait X min before/after indicators)                  |\n';
      code += '//+------------------------------------------------------------------+\n';
      code += 'bool IsNewsTime()\n{\n';
      code += '   static datetime lastUpdate = 0;\n';
      code += '   static string newsXML = "";\n';
      code += '   if(TimeCurrent() - lastUpdate > 3600 || newsXML == "") {\n';
      code += '      char post[], result[]; string head;\n';
      code += '      int res = WebRequest("GET", "https://www.forexfactory.com/ffcal_week_this.xml", NULL, NULL, 5000, post, 0, result, head);\n';
      code += '      if(res != -1) { newsXML = CharArrayToString(result); lastUpdate = TimeCurrent(); }\n';
      code += '   }\n';
      code += '   if(newsXML == "") return false;\n';
      code += '   \n';
      code += '   int start = 0;\n';
      code += '   while((start = StringFind(newsXML, "<event>", start)) != -1) {\n';
      code += '      int end = StringFind(newsXML, "</event>", start);\n';
      code += '      string event = StringSubstr(newsXML, start, end - start);\n';
      code += '      start = end;\n';
      code += '      \n';
      code += '      if(StringFind(event, "<impact>High</impact>") == -1 && \n';
      code += '         StringFind(event, "<impact>Medium</impact>") == -1) continue;\n';
      code += '      \n';
      code += '      int dateStart = StringFind(event, "<date><![CDATA[") + 15;\n';
      code += '      int dateEnd = StringFind(event, "]]></date>", dateStart);\n';
      code += '      string dateStr = StringSubstr(event, dateStart, dateEnd - dateStart);\n';
      code += '      \n';
      code += '      int timeStart = StringFind(event, "<time><![CDATA[") + 15;\n';
      code += '      int timeEnd = StringFind(event, "]]></time>", timeStart);\n';
      code += '      string timeStr = StringSubstr(event, timeStart, timeEnd - timeStart);\n';
      code += '      \n';
      code += '      datetime eventTime = StringToTime(dateStr + " " + timeStr);\n';
      code += '      if(MathAbs(TimeCurrent() - eventTime) < NewsBefore * 60) return true;\n';
      code += '      if(MathAbs(TimeCurrent() - eventTime) < NewsAfter * 60) return true;\n';
      code += '   }\n';
      code += '   return false;\n';
      code += '}\n\n';
    }

    // IsHoliday (Wait for main holidays)
    code += '//+------------------------------------------------------------------+\n';
    code += '//| IsHoliday (Japan & US Holidays Simplified)                       |\n';
    code += '//+------------------------------------------------------------------+\n';
    code += 'bool IsHoliday()\n{\n';
    code += '   MqlDateTime dt;\n';
    code += '   TimeToStruct(TimeCurrent(), dt);\n';
    code += '   \n';
    code += '   // New Year\n';
    code += '   if(dt.mon == 1 && dt.day <= 3) return true;\n';
    code += '   // Christmas\n';
    code += '   if(dt.mon == 12 && dt.day >= 24 && dt.day <= 26) return true;\n';
    code += '   // Golden Week (Japan)\n';
    code += '   if(dt.mon == 5 && dt.day >= 3 && dt.day <= 5) return true;\n';
    code += '   \n';
    code += '   return false;\n';
    code += '}\n\n';

    // Nanpin
    if (state.strategies && state.strategies.includes('nanpin')) {
      code += '//+------------------------------------------------------------------+\n';
      code += '//| Nanpin (Dollar Cost Averaging)                                    |\n';
      code += '//+------------------------------------------------------------------+\n';
      code += 'void CheckNanpin()\n{\n';
      code += '   int buyCount = CountOrders(OP_BUY);\n';
      code += '   int sellCount = CountOrders(OP_SELL);\n';
      code += '   \n';
      code += '   if(buyCount > 0 && buyCount < NanpinMax) {\n';
      code += '      double lastBuyPrice = LastOrderPrice(OP_BUY);\n';
      code += '      if(Ask <= lastBuyPrice - NanpinInterval * Point) {\n';
      code += '         double sl = 0, tp = 0;\n';
      code += '         if(StopLoss > 0)   sl = Ask - StopLoss * Point;\n';
      code += '         if(TakeProfit > 0)  tp = Ask + TakeProfit * Point;\n';
      code += '         OrderSend(Symbol(), OP_BUY, LotSize, Ask, Slippage, sl, tp, "Nanpin", MagicNumber, 0, clrBlue);\n';
      code += '      }\n';
      code += '   }\n';
      code += '   \n';
      code += '   if(sellCount > 0 && sellCount < NanpinMax) {\n';
      code += '      double lastSellPrice = LastOrderPrice(OP_SELL);\n';
      code += '      if(Bid >= lastSellPrice + NanpinInterval * Point) {\n';
      code += '         double sl2 = 0, tp2 = 0;\n';
      code += '         if(StopLoss > 0)   sl2 = Bid + StopLoss * Point;\n';
      code += '         if(TakeProfit > 0)  tp2 = Bid - TakeProfit * Point;\n';
      code += '         OrderSend(Symbol(), OP_SELL, LotSize, Bid, Slippage, sl2, tp2, "Nanpin", MagicNumber, 0, clrRed);\n';
      code += '      }\n';
      code += '   }\n';
      code += '}\n\n';
    }

    // Martingale
    if (state.strategies && state.strategies.includes('martingale')) {
      code += '//+------------------------------------------------------------------+\n';
      code += '//| Martingale                                                        |\n';
      code += '//+------------------------------------------------------------------+\n';
      code += 'double GetMartingaleLot()\n{\n';
      code += '   if(martingaleCount == 0) return LotSize;\n';
      code += '   double lot = LotSize * MathPow(MartingaleMultiplier, martingaleCount);\n';
      code += '   lot = MathMin(lot, MarketInfo(Symbol(), MODE_MAXLOT));\n';
      code += '   lot = MathMax(lot, MarketInfo(Symbol(), MODE_MINLOT));\n';
      code += '   return NormalizeDouble(lot, 2);\n';
      code += '}\n\n';
      code += 'void CheckMartingaleReset()\n{\n';
      code += '   // Check last closed order\n';
      code += '   for(int i = OrdersHistoryTotal() - 1; i >= 0; i--) {\n';
      code += '      if(OrderSelect(i, SELECT_BY_POS, MODE_HISTORY)) {\n';
      code += '         if(OrderSymbol() == Symbol() && OrderMagicNumber() == MagicNumber) {\n';
      code += '            if(OrderProfit() > 0) { martingaleCount = 0; return; }\n';
      code += '            if(OrderProfit() < 0 && martingaleCount < MartingaleMax) { martingaleCount++; return; }\n';
      code += '         }\n';
      code += '      }\n';
      code += '   }\n';
      code += '}\n\n';
    }

    // Grid
    if (state.strategies && state.strategies.includes('grid')) {
      const p = state.positionParams || {};
      code += '//+------------------------------------------------------------------+\n';
      code += '//| Grid Trading                                                      |\n';
      code += '//+------------------------------------------------------------------+\n';
      code += `extern int    GridInterval = ${p.gridInterval || 20};\n`;
      code += `extern int    GridCount    = ${p.gridCount || 5};\n\n`;
      code += 'void CheckGrid()\n{\n';
      code += '   int buyCount = CountOrders(OP_BUY);\n';
      code += '   int sellCount = CountOrders(OP_SELL);\n';
      code += '   \n';
      code += '   if(buyCount > 0 && buyCount < GridCount) {\n';
      code += '      double lastBuyPrice = LastOrderPrice(OP_BUY);\n';
      code += '      if(Ask <= lastBuyPrice - GridInterval * Point) {\n';
      code += '         double sl = 0, tp = 0;\n';
      code += '         if(StopLoss > 0) sl = Ask - StopLoss * Point;\n';
      code += '         if(TakeProfit > 0) tp = Ask + TakeProfit * Point;\n';
      code += '         OrderSend(Symbol(), OP_BUY, LotSize, Ask, Slippage, sl, tp, "Grid", MagicNumber, 0, clrBlue);\n';
      code += '      }\n';
      code += '   }\n';
      code += '   \n';
      code += '   if(sellCount > 0 && sellCount < GridCount) {\n';
      code += '      double lastSellPrice = LastOrderPrice(OP_SELL);\n';
      code += '      if(Bid >= lastSellPrice + GridInterval * Point) {\n';
      code += '         double sl2 = 0, tp2 = 0;\n';
      code += '         if(StopLoss > 0) sl2 = Bid + StopLoss * Point;\n';
      code += '         if(TakeProfit > 0) tp2 = Bid - TakeProfit * Point;\n';
      code += '         OrderSend(Symbol(), OP_SELL, LotSize, Bid, Slippage, sl2, tp2, "Grid", MagicNumber, 0, clrRed);\n';
      code += '      }\n';
      code += '   }\n';
      code += '}\n\n';
    }

    // Discord Webhook
    if (state.useDiscordWebhook) {
      code += '//+------------------------------------------------------------------+\n';
      code += '//| Discord Webhook                                                   |\n';
      code += '//+------------------------------------------------------------------+\n';
      code += '#import "wininet.dll"\n';
      code += '   int InternetOpenW(string, int, string, string, int);\n';
      code += '   int InternetOpenUrlW(int, string, string, int, int, int);\n';
      code += '   int InternetCloseHandle(int);\n';
      code += '#import\n\n';
      code += 'void SendDiscord(string message)\n{\n';
      code += '   string url = "' + (state.discordWebhookURL || '') + '";\n';
      code += '   string payload = "{\\"content\\":\\"" + message + "\\"}";\n';
      code += '   \n';
      code += '   int hInternet = InternetOpenW("EA", 0, "", "", 0);\n';
      code += '   if(hInternet == 0) return;\n';
      code += '   \n';
      code += '   string headers = "Content-Type: application/json\\r\\n";\n';
      code += '   int hRequest = InternetOpenUrlW(hInternet, url + "?" + payload, headers, StringLen(headers), 0, 0);\n';
      code += '   \n';
      code += '   if(hRequest > 0) InternetCloseHandle(hRequest);\n';
      code += '   InternetCloseHandle(hInternet);\n';
      code += '}\n\n';
    }

    code += '   if(state.useAlertEmail) {\n';
    code += '      code += \'   SendMail("EA Alert", message);\\n\';\n';
    code += '   }\n';
    code += '   if(state.useAlertPush) {\n';
    code += '      code += \'   SendNotification(message);\\n\';\n';
    code += '   }\n';
    code += '   if(state.useDiscordWebhook) {\n';
    code += '      code += \'   SendDiscord(message);\\n\';\n';
    code += '   }\n';
    code += '   code += \'}\\n\\n\';\n';
    code += '}\n\n';

    return code;
  },


  // ==================== [G-091] Helper Functions MT5 ====================
  generateHelperFunctionsMT5: function(state) {
    let code = '';

    // Trailing Stop
    if (state.useTrailing) {
      code += '//+------------------------------------------------------------------+\n';
      code += '//| Trailing Stop Function                                            |\n';
      code += '//+------------------------------------------------------------------+\n';
      code += 'void TrailingStopFunc()\n{\n';
      code += '   double point = SymbolInfoDouble(Symbol(), SYMBOL_POINT);\n';
      code += '   for(int i = PositionsTotal() - 1; i >= 0; i--) {\n';
      code += '      ulong ticket = PositionGetTicket(i);\n';
      code += '      if(PositionSelectByTicket(ticket)) {\n';
      code += '         if(PositionGetString(POSITION_SYMBOL) == Symbol() && PositionGetInteger(POSITION_MAGIC) == MagicNumber) {\n';
      code += '            double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);\n';
      code += '            double curSL = PositionGetDouble(POSITION_SL);\n';
      code += '            double curTP = PositionGetDouble(POSITION_TP);\n';
      code += '            if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) {\n';
      code += '               double bid = SymbolInfoDouble(Symbol(), SYMBOL_BID);\n';
      code += '               if(bid - openPrice >= TrailingStart * point) {\n';
      code += '                  double newSL = bid - TrailingWidth * point;\n';
      code += '                  if(curSL == 0 || newSL - curSL >= TrailingStep * point) {\n';
      code += '                     trade.PositionModify(ticket, newSL, curTP);\n';
      code += '                  }\n';
      code += '               }\n';
      code += '            }\n';
      code += '            if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_SELL) {\n';
      code += '               double ask = SymbolInfoDouble(Symbol(), SYMBOL_ASK);\n';
      code += '               if(openPrice - ask >= TrailingStart * point) {\n';
      code += '                  double newSL = ask + TrailingWidth * point;\n';
      code += '                  if(curSL == 0 || curSL - newSL >= TrailingStep * point) {\n';
      code += '                     trade.PositionModify(ticket, newSL, curTP);\n';
      code += '                  }\n';
      code += '               }\n';
      code += '            }\n';
      code += '         }\n';
      code += '      }\n';
      code += '   }\n';
      code += '}\n\n';
    }

    // Close All Positions
    code += '//+------------------------------------------------------------------+\n';
    code += '//| Close All Positions                                               |\n';
    code += '//+------------------------------------------------------------------+\n';
    code += 'void CloseAllPositions(int type = -1)\n{\n';
    code += '   for(int i = PositionsTotal() - 1; i >= 0; i--) {\n';
    code += '      ulong ticket = PositionGetTicket(i);\n';
    code += '      if(PositionSelectByTicket(ticket)) {\n';
    code += '         if(PositionGetString(POSITION_SYMBOL) == Symbol() && PositionGetInteger(POSITION_MAGIC) == MagicNumber) {\n';
    code += '            if(type == -1 || PositionGetInteger(POSITION_TYPE) == type) {\n';
    code += '               trade.PositionClose(ticket);\n';
    code += '            }\n';
    code += '         }\n';
    code += '      }\n';
    code += '   }\n';
    code += '}\n\n';

    // Count Positions
    code += 'int CountPositions(int type = -1)\n{\n';
    code += '   int count = 0;\n';
    code += '   for(int i = PositionsTotal() - 1; i >= 0; i--) {\n';
    code += '      if(PositionSelectByTicket(PositionGetTicket(i))) {\n';
    code += '         if(PositionGetString(POSITION_SYMBOL) == Symbol() && PositionGetInteger(POSITION_MAGIC) == MagicNumber) {\n';
    code += '            if(type == -1 || PositionGetInteger(POSITION_TYPE) == type) count++;\n';
    code += '         }\n';
    code += '      }\n';
    code += '   }\n';
    code += '   return count;\n';
    code += '}\n\n';

    // Total Profit
    code += 'double TotalProfit(int type = -1)\n{\n';
    code += '   double profit = 0;\n';
    code += '   for(int i = PositionsTotal() - 1; i >= 0; i--) {\n';
    code += '      ulong ticket = PositionGetTicket(i);\n';
    code += '      if(PositionGetString(POSITION_SYMBOL) == Symbol() && PositionGetInteger(POSITION_MAGIC) == MagicNumber) {\n';
    code += '         if(type == -1 || PositionGetInteger(POSITION_TYPE) == type) {\n';
    code += '            profit += PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);\n';
    code += '         }\n';
    code += '      }\n';
    code += '   }\n';
    code += '   return profit;\n';
    code += '}\n\n';

    // Last Position Price
    code += 'double LastPositionPrice(int type)\n{\n';
    code += '   datetime lastTime = 0;\n';
    code += '   double lastPrice = 0;\n';
    code += '   for(int i = PositionsTotal() - 1; i >= 0; i--) {\n';
    code += '      ulong ticket = PositionGetTicket(i);\n';
    code += '      if(PositionGetString(POSITION_SYMBOL) == Symbol() && PositionGetInteger(POSITION_MAGIC) == MagicNumber) {\n';
    code += '         if(PositionGetInteger(POSITION_TYPE) == type) {\n';
    code += '            if(PositionGetInteger(POSITION_TIME) > lastTime) {\n';
    code += '               lastTime = (datetime)PositionGetInteger(POSITION_TIME);\n';
    code += '               lastPrice = PositionGetDouble(POSITION_PRICE_OPEN);\n';
    code += '            }\n';
    code += '         }\n';
    code += '      }\n';
    code += '   }\n';
    code += '   return lastPrice;\n';
    code += '}\n\n';
    
    // Helper: Month Filter MT5
    code += '//+------------------------------------------------------------------+\n';
    code += '//| Month-end/Month-start Filter                                     |\n';
    code += '//+------------------------------------------------------------------+\n';
    code += 'bool IsMonthFilterActive()\n{\n';
    code += '   if(!UseMonthFilter) return false;\n';
    code += '   MqlDateTime dt;\n';
    code += '   TimeCurrent(dt);\n';
    code += '   if(dt.day <= MonthStartDays) return true;\n';
    code += '   MqlDateTime future_dt;\n';
    code += '   for(int i = 1; i <= MonthEndDays; i++) {\n';
    code += '      datetime future = TimeCurrent() + 86400 * i;\n';
    code += '      TimeToStruct(future, future_dt);\n';
    code += '      if(future_dt.mon != dt.mon) return true;\n';
    code += '   }\n';
    code += '   return false;\n';
    code += '}\n\n';

    // Helper: Nanpin Profit MT5
    code += 'void CheckNanpinProfit()\n{\n';
    code += '   if(NanpinTargetProfit <= 0) return;\n';
    code += '   double totalProfit = 0;\n';
    code += '   int count = 0;\n';
    code += '   for(int i = PositionsTotal() - 1; i >= 0; i--) {\n';
    code += '      ulong ticket = PositionGetTicket(i);\n';
    code += '      if(PositionGetString(POSITION_SYMBOL) == Symbol() && PositionGetInteger(POSITION_MAGIC) == MagicNumber) {\n';
    code += '         totalProfit += PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);\n';
    code += '         count++;\n';
    code += '      }\n';
    code += '   }\n';
    code += '   if(count > 0 && totalProfit >= NanpinTargetProfit) {\n';
    code += '      CloseAllPositions();\n';
    code += '   }\n';
    code += '}\n\n';


    // Nanpin MT5
    if (state.strategies && state.strategies.includes('nanpin')) {
      code += '//+------------------------------------------------------------------+\n';
      code += '//| Nanpin (Dollar Cost Averaging) MT5                                |\n';
      code += '//+------------------------------------------------------------------+\n';
      code += 'void CheckNanpin()\n{\n';
      code += '   double point = SymbolInfoDouble(Symbol(), SYMBOL_POINT);\n';
      code += '   double ask = SymbolInfoDouble(Symbol(), SYMBOL_ASK);\n';
      code += '   double bid = SymbolInfoDouble(Symbol(), SYMBOL_BID);\n';
      code += '   int buyCount = CountPositions(POSITION_TYPE_BUY);\n';
      code += '   int sellCount = CountPositions(POSITION_TYPE_SELL);\n';
      code += '   \n';
      code += '   if(buyCount > 0 && buyCount < NanpinMax) {\n';
      code += '      double lastBuyPrice = LastPositionPrice(POSITION_TYPE_BUY);\n';
      code += '      if(ask <= lastBuyPrice - NanpinInterval * point) {\n';
      code += '         double sl = 0, tp = 0;\n';
      code += '         if(StopLoss > 0)   sl = ask - StopLoss * point;\n';
      code += '         if(TakeProfit > 0)  tp = ask + TakeProfit * point;\n';
      code += '         trade.Buy(LotSize, Symbol(), ask, sl, tp, "Nanpin");\n';
      code += '      }\n';
      code += '   }\n';
      code += '   \n';
      code += '   if(sellCount > 0 && sellCount < NanpinMax) {\n';
      code += '      double lastSellPrice = LastPositionPrice(POSITION_TYPE_SELL);\n';
      code += '      if(bid >= lastSellPrice + NanpinInterval * point) {\n';
      code += '         double sl2 = 0, tp2 = 0;\n';
      code += '         if(StopLoss > 0)   sl2 = bid + StopLoss * point;\n';
      code += '         if(TakeProfit > 0)  tp2 = bid - TakeProfit * point;\n';
      code += '         trade.Sell(LotSize, Symbol(), bid, sl2, tp2, "Nanpin");\n';
      code += '      }\n';
      code += '   }\n';
      code += '}\n\n';
    }

    // Martingale MT5
    if (state.strategies && state.strategies.includes('martingale')) {
      code += '//+------------------------------------------------------------------+\n';
      code += '//| Martingale MT5                                                    |\n';
      code += '//+------------------------------------------------------------------+\n';
      code += 'double GetMartingaleLot()\n{\n';
      code += '   if(martingaleCount == 0) return LotSize;\n';
      code += '   double lot = LotSize * MathPow(MartingaleMultiplier, martingaleCount);\n';
      code += '   double maxLot = SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_MAX);\n';
      code += '   double minLot = SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_MIN);\n';
      code += '   lot = MathMin(lot, maxLot);\n';
      code += '   lot = MathMax(lot, minLot);\n';
      code += '   return NormalizeDouble(lot, 2);\n';
      code += '}\n\n';
      code += 'void CheckMartingaleReset()\n{\n';
      code += '   if(!HistorySelect(TimeCurrent() - 86400 * 7, TimeCurrent())) return;\n';
      code += '   int total = HistoryDealsTotal();\n';
      code += '   for(int i = total - 1; i >= 0; i--) {\n';
      code += '      ulong dealTicket = HistoryDealGetTicket(i);\n';
      code += '      if(HistoryDealGetString(dealTicket, DEAL_SYMBOL) == Symbol() &&\n';
      code += '         HistoryDealGetInteger(dealTicket, DEAL_MAGIC) == MagicNumber &&\n';
      code += '         HistoryDealGetInteger(dealTicket, DEAL_ENTRY) == DEAL_ENTRY_OUT) {\n';
      code += '         double profit = HistoryDealGetDouble(dealTicket, DEAL_PROFIT);\n';
      code += '         if(profit > 0) { martingaleCount = 0; return; }\n';
      code += '         if(profit < 0 && martingaleCount < MartingaleMax) { martingaleCount++; return; }\n';
      code += '      }\n';
      code += '   }\n';
      code += '}\n\n';
    }

    // Grid MT5
    if (state.strategies && state.strategies.includes('grid')) {
      const p = state.positionParams || {};
      code += '//+------------------------------------------------------------------+\n';
      code += '//| Grid Trading MT5                                                  |\n';
      code += '//+------------------------------------------------------------------+\n';
      code += `input int    GridInterval = ${p.gridInterval || 20};\n`;
      code += `input int    GridCount    = ${p.gridCount || 5};\n\n`;
      code += 'void CheckGrid()\n{\n';
      code += '   double point = SymbolInfoDouble(Symbol(), SYMBOL_POINT);\n';
      code += '   double ask = SymbolInfoDouble(Symbol(), SYMBOL_ASK);\n';
      code += '   double bid = SymbolInfoDouble(Symbol(), SYMBOL_BID);\n';
      code += '   int buyCount = CountPositions(POSITION_TYPE_BUY);\n';
      code += '   int sellCount = CountPositions(POSITION_TYPE_SELL);\n';
      code += '   \n';
      code += '   if(buyCount > 0 && buyCount < GridCount) {\n';
      code += '      double lastBuyPrice = LastPositionPrice(POSITION_TYPE_BUY);\n';
      code += '      if(ask <= lastBuyPrice - GridInterval * point) {\n';
      code += '         double sl = 0, tp = 0;\n';
      code += '         if(StopLoss > 0) sl = ask - StopLoss * point;\n';
      code += '         if(TakeProfit > 0) tp = ask + TakeProfit * point;\n';
      code += '         trade.Buy(LotSize, Symbol(), ask, sl, tp, "Grid");\n';
      code += '      }\n';
      code += '   }\n';
      code += '   \n';
      code += '   if(sellCount > 0 && sellCount < GridCount) {\n';
      code += '      double lastSellPrice = LastPositionPrice(POSITION_TYPE_SELL);\n';
      code += '      if(bid >= lastSellPrice + GridInterval * point) {\n';
      code += '         double sl2 = 0, tp2 = 0;\n';
      code += '         if(StopLoss > 0) sl2 = bid + StopLoss * point;\n';
      code += '         if(TakeProfit > 0) tp2 = bid - TakeProfit * point;\n';
      code += '         trade.Sell(LotSize, Symbol(), bid, sl2, tp2, "Grid");\n';
      code += '      }\n';
      code += '   }\n';
      code += '}\n\n';
    }

    // Discord Webhook MT5
    if (state.useDiscordWebhook) {
      code += '//+------------------------------------------------------------------+\n';
      code += '//| Discord Webhook MT5                                               |\n';
      code += '//+------------------------------------------------------------------+\n';
      code += '#include <\\Web\\WebRequest.mqh>\n\n';
      code += 'void SendDiscord(string message)\n{\n';
      code += '   string url = "' + (state.discordWebhookURL || '') + '";\n';
      code += '   string headers = "Content-Type: application/json\\r\\n";\n';
      code += '   string payload = "{\\"content\\":\\"" + message + "\\"}";\n';
      code += '   char post[];\n';
      code += '   char result[];\n';
      code += '   string resultHeaders;\n';
      code += '   StringToCharArray(payload, post);\n';
      code += '   int res = WebRequest("POST", url, headers, 5000, post, result, resultHeaders);\n';
      code += '   if(res != 200) Print("Discord webhook error: ", res);\n';
      code += '}\n\n';
    }

    // Alert function MT5
    if (state.discordNotifyEntry || state.discordNotifyClose) {
      code += '//+------------------------------------------------------------------+\n';
      code += '//| Send Alert MT5                                                    |\n';
      code += '//+------------------------------------------------------------------+\n';
      code += 'void SendAlert(string message)\n{\n';
      if (state.useAlertPopup) {
        code += '   Alert(message);\n';
      }
      if (state.useAlertSound) {
        code += '   PlaySound("' + (state.alertSoundFile || 'alert.wav') + '");\n';
      }
      if (state.useAlertEmail) {
        code += '   SendMail("EA Alert", message);\n';
      }
      if (state.useAlertPush) {
        code += '   SendNotification(message);\n';
      }
      if (state.useDiscordWebhook) {
        code += '   SendDiscord(message);\n';
      }
      code += '}\n\n';
    }

    return code;
  },


}; // ← EAGenerator object end


// ==================== Module Export ====================
if (typeof module !== 'undefined' && module.exports) {
  module.exports = EAGenerator;
}
if (typeof window !== 'undefined') {
  window.EAGenerator = EAGenerator;
}
